/*
 * AI Core
 * Provides tools to manage your scenarios and workflows in SAP AI Core. Execute pipelines as a batch job, for example to pre-process or train your models, or perform batch inference.  Serve inference requests of trained models. Deploy а trained machine learning model as a web service to serve inference requests with high performance.  Register your own Docker registry, synchronize your AI content from your own git repository, and register your own object store for training data and trained models.
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.ai.sdk.core.model;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/** TntTenantInfo */
// CHECKSTYLE:OFF
public class TntTenantInfo
// CHECKSTYLE:ON
{
  @JsonProperty("tenantId")
  private String tenantId;

  @JsonProperty("servicePlan")
  private String servicePlan;

  @JsonProperty("status")
  private String status;

  @JsonAnySetter @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

  /** Default constructor for TntTenantInfo. */
  protected TntTenantInfo() {}

  /**
   * Set the tenantId of this {@link TntTenantInfo} instance and return the same instance.
   *
   * @param tenantId tenant id
   * @return The same instance of this {@link TntTenantInfo} class
   */
  @Nonnull
  public TntTenantInfo tenantId(@Nonnull final String tenantId) {
    this.tenantId = tenantId;
    return this;
  }

  /**
   * tenant id
   *
   * @return tenantId The tenantId of this {@link TntTenantInfo} instance.
   */
  @Nonnull
  public String getTenantId() {
    return tenantId;
  }

  /**
   * Set the tenantId of this {@link TntTenantInfo} instance.
   *
   * @param tenantId tenant id
   */
  public void setTenantId(@Nonnull final String tenantId) {
    this.tenantId = tenantId;
  }

  /**
   * Set the servicePlan of this {@link TntTenantInfo} instance and return the same instance.
   *
   * @param servicePlan The servicePlan of this {@link TntTenantInfo}
   * @return The same instance of this {@link TntTenantInfo} class
   */
  @Nonnull
  public TntTenantInfo servicePlan(@Nonnull final String servicePlan) {
    this.servicePlan = servicePlan;
    return this;
  }

  /**
   * Get servicePlan
   *
   * @return servicePlan The servicePlan of this {@link TntTenantInfo} instance.
   */
  @Nonnull
  public String getServicePlan() {
    return servicePlan;
  }

  /**
   * Set the servicePlan of this {@link TntTenantInfo} instance.
   *
   * @param servicePlan The servicePlan of this {@link TntTenantInfo}
   */
  public void setServicePlan(@Nonnull final String servicePlan) {
    this.servicePlan = servicePlan;
  }

  /**
   * Set the status of this {@link TntTenantInfo} instance and return the same instance.
   *
   * @param status Provisioning status of the tenant
   * @return The same instance of this {@link TntTenantInfo} class
   */
  @Nonnull
  public TntTenantInfo status(@Nonnull final String status) {
    this.status = status;
    return this;
  }

  /**
   * Provisioning status of the tenant
   *
   * @return status The status of this {@link TntTenantInfo} instance.
   */
  @Nonnull
  public String getStatus() {
    return status;
  }

  /**
   * Set the status of this {@link TntTenantInfo} instance.
   *
   * @param status Provisioning status of the tenant
   */
  public void setStatus(@Nonnull final String status) {
    this.status = status;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link TntTenantInfo}.
   *
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link TntTenantInfo} instance.
   *
   * @deprecated Use {@link #toMap()} instead.
   * @param name The name of the property
   * @return The value of the property
   * @throws NoSuchElementException If no property with the given name could be found.
   */
  @Nullable
  @Deprecated
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if (!cloudSdkCustomFields.containsKey(name)) {
      throw new NoSuchElementException("TntTenantInfo has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Get the value of all properties of this {@link TntTenantInfo} instance including unrecognized
   * properties.
   *
   * @return The map of all properties
   */
  @JsonIgnore
  @Nonnull
  public Map<String, Object> toMap() {
    final Map<String, Object> declaredFields = new LinkedHashMap<>(cloudSdkCustomFields);
    if (tenantId != null) declaredFields.put("tenantId", tenantId);
    if (servicePlan != null) declaredFields.put("servicePlan", servicePlan);
    if (status != null) declaredFields.put("status", status);
    return declaredFields;
  }

  /**
   * Set an unrecognizable property of this {@link TntTenantInfo} instance. If the map previously
   * contained a mapping for the key, the old value is replaced by the specified value.
   *
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField(@Nonnull String customFieldName, @Nullable Object customFieldValue) {
    cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }

  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final TntTenantInfo tntTenantInfo = (TntTenantInfo) o;
    return Objects.equals(this.cloudSdkCustomFields, tntTenantInfo.cloudSdkCustomFields)
        && Objects.equals(this.tenantId, tntTenantInfo.tenantId)
        && Objects.equals(this.servicePlan, tntTenantInfo.servicePlan)
        && Objects.equals(this.status, tntTenantInfo.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tenantId, servicePlan, status, cloudSdkCustomFields);
  }

  @Override
  @Nonnull
  public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class TntTenantInfo {\n");
    sb.append("    tenantId: ").append(toIndentedString(tenantId)).append("\n");
    sb.append("    servicePlan: ").append(toIndentedString(servicePlan)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    cloudSdkCustomFields.forEach(
        (k, v) ->
            sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Create a type-safe, fluent-api builder object to construct a new {@link TntTenantInfo} instance
   * with all required arguments.
   */
  public static Builder create() {
    return (tenantId) ->
        (servicePlan) ->
            (status) ->
                new TntTenantInfo().tenantId(tenantId).servicePlan(servicePlan).status(status);
  }

  /** Builder helper class. */
  public interface Builder {
    /**
     * Set the tenantId of this {@link TntTenantInfo} instance.
     *
     * @param tenantId tenant id
     * @return The TntTenantInfo builder.
     */
    Builder1 tenantId(@Nonnull final String tenantId);
  }

  /** Builder helper class. */
  public interface Builder1 {
    /**
     * Set the servicePlan of this {@link TntTenantInfo} instance.
     *
     * @param servicePlan The servicePlan of this {@link TntTenantInfo}
     * @return The TntTenantInfo builder.
     */
    Builder2 servicePlan(@Nonnull final String servicePlan);
  }

  /** Builder helper class. */
  public interface Builder2 {
    /**
     * Set the status of this {@link TntTenantInfo} instance.
     *
     * @param status Provisioning status of the tenant
     * @return The TntTenantInfo instance.
     */
    TntTenantInfo status(@Nonnull final String status);
  }
}
