/*
 * Document Grounding Pipeline API
 * SAP AI Core - API Specification AI Data Management api's
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.ai.sdk.grounding.model;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.annotations.Beta;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import java.util.UUID;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/** A logical grouping of content. */
@Beta // CHECKSTYLE:OFF
public class Collection
// CHECKSTYLE:ON
{
  @JsonProperty("title")
  private String title;

  @JsonProperty("embeddingConfig")
  private EmbeddingConfig embeddingConfig;

  @JsonProperty("metadata")
  private List<KeyValueListPair> metadata = new ArrayList<>();

  @JsonProperty("id")
  private UUID id;

  @JsonAnySetter @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

  /** Default constructor for Collection. */
  protected Collection() {}

  /**
   * Set the title of this {@link Collection} instance and return the same instance.
   *
   * @param title The title of this {@link Collection}
   * @return The same instance of this {@link Collection} class
   */
  @Nonnull
  public Collection title(@Nullable final String title) {
    this.title = title;
    return this;
  }

  /**
   * Get title
   *
   * @return title The title of this {@link Collection} instance.
   */
  @Nonnull
  public String getTitle() {
    return title;
  }

  /**
   * Set the title of this {@link Collection} instance.
   *
   * @param title The title of this {@link Collection}
   */
  public void setTitle(@Nullable final String title) {
    this.title = title;
  }

  /**
   * Set the embeddingConfig of this {@link Collection} instance and return the same instance.
   *
   * @param embeddingConfig The embeddingConfig of this {@link Collection}
   * @return The same instance of this {@link Collection} class
   */
  @Nonnull
  public Collection embeddingConfig(@Nonnull final EmbeddingConfig embeddingConfig) {
    this.embeddingConfig = embeddingConfig;
    return this;
  }

  /**
   * Get embeddingConfig
   *
   * @return embeddingConfig The embeddingConfig of this {@link Collection} instance.
   */
  @Nonnull
  public EmbeddingConfig getEmbeddingConfig() {
    return embeddingConfig;
  }

  /**
   * Set the embeddingConfig of this {@link Collection} instance.
   *
   * @param embeddingConfig The embeddingConfig of this {@link Collection}
   */
  public void setEmbeddingConfig(@Nonnull final EmbeddingConfig embeddingConfig) {
    this.embeddingConfig = embeddingConfig;
  }

  /**
   * Set the metadata of this {@link Collection} instance and return the same instance.
   *
   * @param metadata Metadata attached to collection. Useful to restrict search to a subset of
   *     collections.
   * @return The same instance of this {@link Collection} class
   */
  @Nonnull
  public Collection metadata(@Nullable final List<KeyValueListPair> metadata) {
    this.metadata = metadata;
    return this;
  }

  /**
   * Add one metadata instance to this {@link Collection}.
   *
   * @param metadataItem The metadata that should be added
   * @return The same instance of type {@link Collection}
   */
  @Nonnull
  public Collection addMetadataItem(@Nonnull final KeyValueListPair metadataItem) {
    if (this.metadata == null) {
      this.metadata = new ArrayList<>();
    }
    this.metadata.add(metadataItem);
    return this;
  }

  /**
   * Metadata attached to collection. Useful to restrict search to a subset of collections.
   *
   * @return metadata The metadata of this {@link Collection} instance.
   */
  @Nonnull
  public List<KeyValueListPair> getMetadata() {
    return metadata;
  }

  /**
   * Set the metadata of this {@link Collection} instance.
   *
   * @param metadata Metadata attached to collection. Useful to restrict search to a subset of
   *     collections.
   */
  public void setMetadata(@Nullable final List<KeyValueListPair> metadata) {
    this.metadata = metadata;
  }

  /**
   * Set the id of this {@link Collection} instance and return the same instance.
   *
   * @param id Unique identifier of a collection.
   * @return The same instance of this {@link Collection} class
   */
  @Nonnull
  public Collection id(@Nonnull final UUID id) {
    this.id = id;
    return this;
  }

  /**
   * Unique identifier of a collection.
   *
   * @return id The id of this {@link Collection} instance.
   */
  @Nonnull
  public UUID getId() {
    return id;
  }

  /**
   * Set the id of this {@link Collection} instance.
   *
   * @param id Unique identifier of a collection.
   */
  public void setId(@Nonnull final UUID id) {
    this.id = id;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link Collection}.
   *
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link Collection} instance.
   *
   * @param name The name of the property
   * @return The value of the property
   * @throws NoSuchElementException If no property with the given name could be found.
   */
  @Nullable
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if (!cloudSdkCustomFields.containsKey(name)) {
      throw new NoSuchElementException("Collection has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Set an unrecognizable property of this {@link Collection} instance. If the map previously
   * contained a mapping for the key, the old value is replaced by the specified value.
   *
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField(@Nonnull String customFieldName, @Nullable Object customFieldValue) {
    cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }

  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final Collection collection = (Collection) o;
    return Objects.equals(this.cloudSdkCustomFields, collection.cloudSdkCustomFields)
        && Objects.equals(this.title, collection.title)
        && Objects.equals(this.embeddingConfig, collection.embeddingConfig)
        && Objects.equals(this.metadata, collection.metadata)
        && Objects.equals(this.id, collection.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(title, embeddingConfig, metadata, id, cloudSdkCustomFields);
  }

  @Override
  @Nonnull
  public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class Collection {\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    embeddingConfig: ").append(toIndentedString(embeddingConfig)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    cloudSdkCustomFields.forEach(
        (k, v) ->
            sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Create a type-safe, fluent-api builder object to construct a new {@link Collection} instance
   * with all required arguments.
   */
  public static Builder create() {
    return (embeddingConfig) -> (id) -> new Collection().embeddingConfig(embeddingConfig).id(id);
  }

  /** Builder helper class. */
  public interface Builder {
    /**
     * Set the embeddingConfig of this {@link Collection} instance.
     *
     * @param embeddingConfig The embeddingConfig of this {@link Collection}
     * @return The Collection builder.
     */
    Builder1 embeddingConfig(@Nonnull final EmbeddingConfig embeddingConfig);
  }

  /** Builder helper class. */
  public interface Builder1 {
    /**
     * Set the id of this {@link Collection} instance.
     *
     * @param id Unique identifier of a collection.
     * @return The Collection instance.
     */
    Collection id(@Nonnull final UUID id);
  }
}
