/*
 * Copyright (c) 2025 SAP SE or an SAP affiliate company. All rights reserved.
 */

/*
 * Document Grounding Pipeline API
 * SAP AI Core - API Specification AI Data Management api's
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package openapi.grounding.model;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.sap.cloud.sdk.datamodel.openapi.grounding.model.PipelineConfigurationSharePoint;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/** PipelineConfiguration */
// CHECKSTYLE:OFF
public class PipelineConfiguration
// CHECKSTYLE:ON
{
  @JsonProperty("destination")
  private String destination;

  @JsonProperty("sharePoint")
  private PipelineConfigurationSharePoint sharePoint;

  @JsonAnySetter @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

  /** Default constructor for PipelineConfiguration. */
  private PipelineConfiguration() {}

  /**
   * Set the destination of this {@link PipelineConfiguration} instance and return the same
   * instance.
   *
   * @param destination The destination of this {@link PipelineConfiguration}
   * @return The same instance of this {@link PipelineConfiguration} class
   */
  @Nonnull
  public PipelineConfiguration destination(@Nullable final String destination) {
    this.destination = destination;
    return this;
  }

  /**
   * Get destination
   *
   * @return destination The destination of this {@link PipelineConfiguration} instance.
   */
  @Nonnull
  public String getDestination() {
    return destination;
  }

  /**
   * Set the destination of this {@link PipelineConfiguration} instance.
   *
   * @param destination The destination of this {@link PipelineConfiguration}
   */
  public void setDestination(@Nullable final String destination) {
    this.destination = destination;
  }

  /**
   * Set the sharePoint of this {@link PipelineConfiguration} instance and return the same instance.
   *
   * @param sharePoint The sharePoint of this {@link PipelineConfiguration}
   * @return The same instance of this {@link PipelineConfiguration} class
   */
  @Nonnull
  public PipelineConfiguration sharePoint(
      @Nullable final PipelineConfigurationSharePoint sharePoint) {
    this.sharePoint = sharePoint;
    return this;
  }

  /**
   * Get sharePoint
   *
   * @return sharePoint The sharePoint of this {@link PipelineConfiguration} instance.
   */
  @Nonnull
  public PipelineConfigurationSharePoint getSharePoint() {
    return sharePoint;
  }

  /**
   * Set the sharePoint of this {@link PipelineConfiguration} instance.
   *
   * @param sharePoint The sharePoint of this {@link PipelineConfiguration}
   */
  public void setSharePoint(@Nullable final PipelineConfigurationSharePoint sharePoint) {
    this.sharePoint = sharePoint;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link PipelineConfiguration}.
   *
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link PipelineConfiguration} instance.
   *
   * @param name The name of the property
   * @return The value of the property
   * @throws NoSuchElementException If no property with the given name could be found.
   */
  @Nullable
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if (!cloudSdkCustomFields.containsKey(name)) {
      throw new NoSuchElementException(
          "PipelineConfiguration has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Set an unrecognizable property of this {@link PipelineConfiguration} instance. If the map
   * previously contained a mapping for the key, the old value is replaced by the specified value.
   *
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField(@Nonnull String customFieldName, @Nullable Object customFieldValue) {
    cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }

  @Override
  public boolean equals(@Nullable final Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final PipelineConfiguration pipelineConfiguration = (PipelineConfiguration) o;
    return Objects.equals(this.cloudSdkCustomFields, pipelineConfiguration.cloudSdkCustomFields)
        && Objects.equals(this.destination, pipelineConfiguration.destination)
        && Objects.equals(this.sharePoint, pipelineConfiguration.sharePoint);
  }

  @Override
  public int hashCode() {
    return Objects.hash(destination, sharePoint, cloudSdkCustomFields);
  }

  @Override
  @Nonnull
  public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class PipelineConfiguration {\n");
    sb.append("    destination: ").append(toIndentedString(destination)).append("\n");
    sb.append("    sharePoint: ").append(toIndentedString(sharePoint)).append("\n");
    cloudSdkCustomFields.forEach(
        (k, v) ->
            sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(final Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /** Create a new {@link PipelineConfiguration} instance. No arguments are required. */
  public static PipelineConfiguration builder() {
    return new PipelineConfiguration();
  }
}
