/*
 * Copyright (c) 2025 SAP SE or an SAP affiliate company. All rights reserved.
 */

/*
 * Document Grounding Pipeline API
 * SAP AI Core - API Specification AI Data Management api's
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package openapi.grounding.model;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.sap.cloud.sdk.datamodel.openapi.grounding.model.ResultsInner1;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/** RetievalSearchResults */
// CHECKSTYLE:OFF
public class RetievalSearchResults
// CHECKSTYLE:ON
{
  @JsonProperty("results")
  private List<ResultsInner1> results = new ArrayList<>();

  @JsonAnySetter @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

  /** Default constructor for RetievalSearchResults. */
  private RetievalSearchResults() {}

  /**
   * Set the results of this {@link RetievalSearchResults} instance and return the same instance.
   *
   * @param results List of returned results.
   * @return The same instance of this {@link RetievalSearchResults} class
   */
  @Nonnull
  public RetievalSearchResults results(@Nonnull final List<ResultsInner1> results) {
    this.results = results;
    return this;
  }

  /**
   * Add one results instance to this {@link RetievalSearchResults}.
   *
   * @param resultsItem The results that should be added
   * @return The same instance of type {@link RetievalSearchResults}
   */
  @Nonnull
  public RetievalSearchResults addResultsItem(@Nonnull final ResultsInner1 resultsItem) {
    if (this.results == null) {
      this.results = new ArrayList<>();
    }
    this.results.add(resultsItem);
    return this;
  }

  /**
   * List of returned results.
   *
   * @return results The results of this {@link RetievalSearchResults} instance.
   */
  @Nonnull
  public List<ResultsInner1> getResults() {
    return results;
  }

  /**
   * Set the results of this {@link RetievalSearchResults} instance.
   *
   * @param results List of returned results.
   */
  public void setResults(@Nonnull final List<ResultsInner1> results) {
    this.results = results;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link RetievalSearchResults}.
   *
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link RetievalSearchResults} instance.
   *
   * @param name The name of the property
   * @return The value of the property
   * @throws NoSuchElementException If no property with the given name could be found.
   */
  @Nullable
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if (!cloudSdkCustomFields.containsKey(name)) {
      throw new NoSuchElementException(
          "RetievalSearchResults has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Set an unrecognizable property of this {@link RetievalSearchResults} instance. If the map
   * previously contained a mapping for the key, the old value is replaced by the specified value.
   *
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField(@Nonnull String customFieldName, @Nullable Object customFieldValue) {
    cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }

  @Override
  public boolean equals(@Nullable final Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final RetievalSearchResults retievalSearchResults = (RetievalSearchResults) o;
    return Objects.equals(this.cloudSdkCustomFields, retievalSearchResults.cloudSdkCustomFields)
        && Objects.equals(this.results, retievalSearchResults.results);
  }

  @Override
  public int hashCode() {
    return Objects.hash(results, cloudSdkCustomFields);
  }

  @Override
  @Nonnull
  public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class RetievalSearchResults {\n");
    sb.append("    results: ").append(toIndentedString(results)).append("\n");
    cloudSdkCustomFields.forEach(
        (k, v) ->
            sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(final Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Create a type-safe, fluent-api builder object to construct a new {@link RetievalSearchResults}
   * instance with all required arguments.
   */
  public static Builder builder() {
    return (results) -> () -> new RetievalSearchResults().results(results);
  }

  /** Builder helper class. */
  public interface Builder {
    /**
     * Set the results of this {@link RetievalSearchResults} instance.
     *
     * @param results List of returned results.
     * @return The RetievalSearchResults instance.
     */
    Builder1 results(@Nonnull final List<ResultsInner1> results);

    /**
     * Set the results of this {@link RetievalSearchResults} instance.
     *
     * @param results List of returned results.
     * @return The RetievalSearchResults instance.
     */
    default Builder1 results(@Nonnull final ResultsInner1... results) {
      return results(Arrays.asList(results));
    }
  }

  /** Builder helper class. */
  public interface Builder1 {
    /**
     * Finalize the builder for new {@link RetievalSearchResults} instance.
     *
     * @return The RetievalSearchResults instance.
     */
    RetievalSearchResults build();
  }
}
