steps:
  detectExecuteScan:
    projectName: 'SHC - CLOUD SDK'
    groups:
      - 'CLOUD SDK 4.0'
    serverUrl: 'https://sap.blackducksoftware.com/'
    mavenExcludedScopes: ["provided", "test"]
    failOn: ['BLOCKER', 'CRITICAL', 'MAJOR']
    versioningModel: "major"
    detectTools: ['DETECTOR', 'BINARY_SCAN']

stages:
  test:
    coverageThresholds:
      instruction: 14
      branch: 3
      complexity: 12
      line: 46
      method: 33
      class: 67