steps:
  detectExecuteScan:
    projectName: 'SHC - CLOUD SDK'
    groups:
      - 'CLOUD SDK 4.0'
    serverUrl: 'https://sap.blackducksoftware.com/'
    mavenExcludedScopes: ["provided", "test"]
    failOn: ['BLOCKER', 'CRITICAL', 'MAJOR']
    versioningModel: "major"
    detectTools: ['DETECTOR', 'BINARY_SCAN']

stages:
  codeCheck:
    checkstyle:
      high: '0'
      normal: '0'
      low: '0'
    spotbugs:
      high: '0'
      normal: '0'
      low: '0'
    pmd:
      high: '0'
      normal: '0'
      low: '0'
