/*
 * Prompt Registry API
 * Prompt Storage service for Design time & Runtime prompt templates.
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.ai.sdk.prompt.registry.model;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/** SchemasTextContent */
// CHECKSTYLE:OFF
public class SchemasTextContent
// CHECKSTYLE:ON
{
  /** Gets or Sets type */
  public enum TypeEnum {
    /** The TEXT option of this SchemasTextContent */
    TEXT("text"),

    /** The UNKNOWN_DEFAULT_OPEN_API option of this SchemasTextContent */
    UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    /**
     * Get the value of the enum
     *
     * @return The enum value
     */
    @JsonValue
    @Nonnull
    public String getValue() {
      return value;
    }

    /**
     * Get the String value of the enum value.
     *
     * @return The enum value as String
     */
    @Override
    @Nonnull
    public String toString() {
      return String.valueOf(value);
    }

    /**
     * Get the enum value from a String value
     *
     * @param value The String value
     * @return The enum value of type SchemasTextContent
     */
    @JsonCreator
    @Nonnull
    public static TypeEnum fromValue(@Nonnull final String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return UNKNOWN_DEFAULT_OPEN_API;
    }
  }

  @JsonProperty("type")
  private TypeEnum type;

  @JsonProperty("text")
  private String text;

  @JsonProperty("cache_control")
  private CacheControl cacheControl;

  @JsonAnySetter @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

  /** Default constructor for SchemasTextContent. */
  protected SchemasTextContent() {}

  /**
   * Set the type of this {@link SchemasTextContent} instance and return the same instance.
   *
   * @param type The type of this {@link SchemasTextContent}
   * @return The same instance of this {@link SchemasTextContent} class
   */
  @Nonnull
  public SchemasTextContent type(@Nonnull final TypeEnum type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   *
   * @return type The type of this {@link SchemasTextContent} instance.
   */
  @Nonnull
  public TypeEnum getType() {
    return type;
  }

  /**
   * Set the type of this {@link SchemasTextContent} instance.
   *
   * @param type The type of this {@link SchemasTextContent}
   */
  public void setType(@Nonnull final TypeEnum type) {
    this.type = type;
  }

  /**
   * Set the text of this {@link SchemasTextContent} instance and return the same instance.
   *
   * @param text The text of this {@link SchemasTextContent}
   * @return The same instance of this {@link SchemasTextContent} class
   */
  @Nonnull
  public SchemasTextContent text(@Nonnull final String text) {
    this.text = text;
    return this;
  }

  /**
   * Get text
   *
   * @return text The text of this {@link SchemasTextContent} instance.
   */
  @Nonnull
  public String getText() {
    return text;
  }

  /**
   * Set the text of this {@link SchemasTextContent} instance.
   *
   * @param text The text of this {@link SchemasTextContent}
   */
  public void setText(@Nonnull final String text) {
    this.text = text;
  }

  /**
   * Set the cacheControl of this {@link SchemasTextContent} instance and return the same instance.
   *
   * @param cacheControl The cacheControl of this {@link SchemasTextContent}
   * @return The same instance of this {@link SchemasTextContent} class
   */
  @Nonnull
  public SchemasTextContent cacheControl(@Nullable final CacheControl cacheControl) {
    this.cacheControl = cacheControl;
    return this;
  }

  /**
   * Get cacheControl
   *
   * @return cacheControl The cacheControl of this {@link SchemasTextContent} instance.
   */
  @Nonnull
  public CacheControl getCacheControl() {
    return cacheControl;
  }

  /**
   * Set the cacheControl of this {@link SchemasTextContent} instance.
   *
   * @param cacheControl The cacheControl of this {@link SchemasTextContent}
   */
  public void setCacheControl(@Nullable final CacheControl cacheControl) {
    this.cacheControl = cacheControl;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link SchemasTextContent}.
   *
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link SchemasTextContent} instance.
   *
   * @deprecated Use {@link #toMap()} instead.
   * @param name The name of the property
   * @return The value of the property
   * @throws NoSuchElementException If no property with the given name could be found.
   */
  @Nullable
  @Deprecated
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if (!cloudSdkCustomFields.containsKey(name)) {
      throw new NoSuchElementException("SchemasTextContent has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Get the value of all properties of this {@link SchemasTextContent} instance including
   * unrecognized properties.
   *
   * @return The map of all properties
   */
  @JsonIgnore
  @Nonnull
  public Map<String, Object> toMap() {
    final Map<String, Object> declaredFields = new LinkedHashMap<>(cloudSdkCustomFields);
    if (type != null) declaredFields.put("type", type);
    if (text != null) declaredFields.put("text", text);
    if (cacheControl != null) declaredFields.put("cacheControl", cacheControl);
    return declaredFields;
  }

  /**
   * Set an unrecognizable property of this {@link SchemasTextContent} instance. If the map
   * previously contained a mapping for the key, the old value is replaced by the specified value.
   *
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField(@Nonnull String customFieldName, @Nullable Object customFieldValue) {
    cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }

  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final SchemasTextContent schemasTextContent = (SchemasTextContent) o;
    return Objects.equals(this.cloudSdkCustomFields, schemasTextContent.cloudSdkCustomFields)
        && Objects.equals(this.type, schemasTextContent.type)
        && Objects.equals(this.text, schemasTextContent.text)
        && Objects.equals(this.cacheControl, schemasTextContent.cacheControl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, text, cacheControl, cloudSdkCustomFields);
  }

  @Override
  @Nonnull
  public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class SchemasTextContent {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    cacheControl: ").append(toIndentedString(cacheControl)).append("\n");
    cloudSdkCustomFields.forEach(
        (k, v) ->
            sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Create a type-safe, fluent-api builder object to construct a new {@link SchemasTextContent}
   * instance with all required arguments.
   */
  public static Builder create() {
    return (type) -> (text) -> new SchemasTextContent().type(type).text(text);
  }

  /** Builder helper class. */
  public interface Builder {
    /**
     * Set the type of this {@link SchemasTextContent} instance.
     *
     * @param type The type of this {@link SchemasTextContent}
     * @return The SchemasTextContent builder.
     */
    Builder1 type(@Nonnull final TypeEnum type);
  }

  /** Builder helper class. */
  public interface Builder1 {
    /**
     * Set the text of this {@link SchemasTextContent} instance.
     *
     * @param text The text of this {@link SchemasTextContent}
     * @return The SchemasTextContent instance.
     */
    SchemasTextContent text(@Nonnull final String text);
  }
}
