name: Question
description: Ask a question about the SAP Cloud SDK for AI  (Java).
labels:
  - question
body:
  - type: markdown
    attributes:
      value: |
        This repository is for Java related issues only. Please open [JavaScript / TypeScript issues here](https://github.com/SAP/ai-sdk-js/issues/new/choose)
  - type: textarea
    attributes:
      label: "Describe the Question"
      description: A clear and concise description of your question.
    validations:
      required: true
