/*
 * Grounding
 * Grounding is a service designed to handle data-related tasks, such as grounding and retrieval, using vector databases. It provides specialized data retrieval through these databases, grounding the retrieval process with your own external and context-relevant data. Grounding combines generative AI capabilities with the ability to use real-time, precise data to improve decision-making and business operations for specific AI-driven business solutions.
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.ai.sdk.grounding.model;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/** ConfigurationDocumentFullDetails */
// CHECKSTYLE:OFF
public class ConfigurationDocumentFullDetails
// CHECKSTYLE:ON
{
  @JsonProperty("id")
  private String id;

  @JsonProperty("title")
  private String title;

  @JsonProperty("absoluteFilePath")
  private String absoluteFilePath;

  @JsonProperty("createdTimestamp")
  private OffsetDateTime createdTimestamp;

  @JsonProperty("resourceUri")
  private String resourceUri;

  @JsonProperty("webUrl")
  private String webUrl;

  @JsonProperty("documentEtag")
  private String documentEtag;

  @JsonProperty("fileSuffix")
  private String fileSuffix;

  @JsonProperty("viewLocation")
  private String viewLocation;

  @JsonProperty("downloadLocation")
  private String downloadLocation;

  @JsonProperty("mimeType")
  private String mimeType;

  @JsonProperty("fileSizeMb")
  private String fileSizeMb;

  @JsonProperty("metadata")
  private List<DocumentMetadata> metadata = new ArrayList<>();

  @JsonAnySetter @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

  /** Default constructor for ConfigurationDocumentFullDetails. */
  protected ConfigurationDocumentFullDetails() {}

  /**
   * Set the id of this {@link ConfigurationDocumentFullDetails} instance and return the same
   * instance.
   *
   * @param id Unique identifier for the document.
   * @return The same instance of this {@link ConfigurationDocumentFullDetails} class
   */
  @Nonnull
  public ConfigurationDocumentFullDetails id(@Nullable final String id) {
    this.id = id;
    return this;
  }

  /**
   * Unique identifier for the document.
   *
   * @return id The id of this {@link ConfigurationDocumentFullDetails} instance.
   */
  @Nonnull
  public String getId() {
    return id;
  }

  /**
   * Set the id of this {@link ConfigurationDocumentFullDetails} instance.
   *
   * @param id Unique identifier for the document.
   */
  public void setId(@Nullable final String id) {
    this.id = id;
  }

  /**
   * Set the title of this {@link ConfigurationDocumentFullDetails} instance and return the same
   * instance.
   *
   * @param title Title of the document.
   * @return The same instance of this {@link ConfigurationDocumentFullDetails} class
   */
  @Nonnull
  public ConfigurationDocumentFullDetails title(@Nullable final String title) {
    this.title = title;
    return this;
  }

  /**
   * Title of the document.
   *
   * @return title The title of this {@link ConfigurationDocumentFullDetails} instance.
   */
  @Nonnull
  public String getTitle() {
    return title;
  }

  /**
   * Set the title of this {@link ConfigurationDocumentFullDetails} instance.
   *
   * @param title Title of the document.
   */
  public void setTitle(@Nullable final String title) {
    this.title = title;
  }

  /**
   * Set the absoluteFilePath of this {@link ConfigurationDocumentFullDetails} instance and return
   * the same instance.
   *
   * @param absoluteFilePath Absolute file path of the document in the repository.
   * @return The same instance of this {@link ConfigurationDocumentFullDetails} class
   */
  @Nonnull
  public ConfigurationDocumentFullDetails absoluteFilePath(
      @Nullable final String absoluteFilePath) {
    this.absoluteFilePath = absoluteFilePath;
    return this;
  }

  /**
   * Absolute file path of the document in the repository.
   *
   * @return absoluteFilePath The absoluteFilePath of this {@link ConfigurationDocumentFullDetails}
   *     instance.
   */
  @Nonnull
  public String getAbsoluteFilePath() {
    return absoluteFilePath;
  }

  /**
   * Set the absoluteFilePath of this {@link ConfigurationDocumentFullDetails} instance.
   *
   * @param absoluteFilePath Absolute file path of the document in the repository.
   */
  public void setAbsoluteFilePath(@Nullable final String absoluteFilePath) {
    this.absoluteFilePath = absoluteFilePath;
  }

  /**
   * Set the createdTimestamp of this {@link ConfigurationDocumentFullDetails} instance and return
   * the same instance.
   *
   * @param createdTimestamp UTC timestamp when the document was created (RFC 3339 format, e.g.,
   *     2025-08-28T06:15:30Z)
   * @return The same instance of this {@link ConfigurationDocumentFullDetails} class
   */
  @Nonnull
  public ConfigurationDocumentFullDetails createdTimestamp(
      @Nullable final OffsetDateTime createdTimestamp) {
    this.createdTimestamp = createdTimestamp;
    return this;
  }

  /**
   * UTC timestamp when the document was created (RFC 3339 format, e.g., 2025-08-28T06:15:30Z)
   *
   * @return createdTimestamp The createdTimestamp of this {@link ConfigurationDocumentFullDetails}
   *     instance.
   */
  @Nonnull
  public OffsetDateTime getCreatedTimestamp() {
    return createdTimestamp;
  }

  /**
   * Set the createdTimestamp of this {@link ConfigurationDocumentFullDetails} instance.
   *
   * @param createdTimestamp UTC timestamp when the document was created (RFC 3339 format, e.g.,
   *     2025-08-28T06:15:30Z)
   */
  public void setCreatedTimestamp(@Nullable final OffsetDateTime createdTimestamp) {
    this.createdTimestamp = createdTimestamp;
  }

  /**
   * Set the resourceUri of this {@link ConfigurationDocumentFullDetails} instance and return the
   * same instance.
   *
   * @param resourceUri URI of the resource.
   * @return The same instance of this {@link ConfigurationDocumentFullDetails} class
   */
  @Nonnull
  public ConfigurationDocumentFullDetails resourceUri(@Nullable final String resourceUri) {
    this.resourceUri = resourceUri;
    return this;
  }

  /**
   * URI of the resource.
   *
   * @return resourceUri The resourceUri of this {@link ConfigurationDocumentFullDetails} instance.
   */
  @Nonnull
  public String getResourceUri() {
    return resourceUri;
  }

  /**
   * Set the resourceUri of this {@link ConfigurationDocumentFullDetails} instance.
   *
   * @param resourceUri URI of the resource.
   */
  public void setResourceUri(@Nullable final String resourceUri) {
    this.resourceUri = resourceUri;
  }

  /**
   * Set the webUrl of this {@link ConfigurationDocumentFullDetails} instance and return the same
   * instance.
   *
   * @param webUrl Web URL of the document.
   * @return The same instance of this {@link ConfigurationDocumentFullDetails} class
   */
  @Nonnull
  public ConfigurationDocumentFullDetails webUrl(@Nullable final String webUrl) {
    this.webUrl = webUrl;
    return this;
  }

  /**
   * Web URL of the document.
   *
   * @return webUrl The webUrl of this {@link ConfigurationDocumentFullDetails} instance.
   */
  @Nonnull
  public String getWebUrl() {
    return webUrl;
  }

  /**
   * Set the webUrl of this {@link ConfigurationDocumentFullDetails} instance.
   *
   * @param webUrl Web URL of the document.
   */
  public void setWebUrl(@Nullable final String webUrl) {
    this.webUrl = webUrl;
  }

  /**
   * Set the documentEtag of this {@link ConfigurationDocumentFullDetails} instance and return the
   * same instance.
   *
   * @param documentEtag ETag of the document.
   * @return The same instance of this {@link ConfigurationDocumentFullDetails} class
   */
  @Nonnull
  public ConfigurationDocumentFullDetails documentEtag(@Nullable final String documentEtag) {
    this.documentEtag = documentEtag;
    return this;
  }

  /**
   * ETag of the document.
   *
   * @return documentEtag The documentEtag of this {@link ConfigurationDocumentFullDetails}
   *     instance.
   */
  @Nonnull
  public String getDocumentEtag() {
    return documentEtag;
  }

  /**
   * Set the documentEtag of this {@link ConfigurationDocumentFullDetails} instance.
   *
   * @param documentEtag ETag of the document.
   */
  public void setDocumentEtag(@Nullable final String documentEtag) {
    this.documentEtag = documentEtag;
  }

  /**
   * Set the fileSuffix of this {@link ConfigurationDocumentFullDetails} instance and return the
   * same instance.
   *
   * @param fileSuffix File suffix of the document.
   * @return The same instance of this {@link ConfigurationDocumentFullDetails} class
   */
  @Nonnull
  public ConfigurationDocumentFullDetails fileSuffix(@Nullable final String fileSuffix) {
    this.fileSuffix = fileSuffix;
    return this;
  }

  /**
   * File suffix of the document.
   *
   * @return fileSuffix The fileSuffix of this {@link ConfigurationDocumentFullDetails} instance.
   */
  @Nonnull
  public String getFileSuffix() {
    return fileSuffix;
  }

  /**
   * Set the fileSuffix of this {@link ConfigurationDocumentFullDetails} instance.
   *
   * @param fileSuffix File suffix of the document.
   */
  public void setFileSuffix(@Nullable final String fileSuffix) {
    this.fileSuffix = fileSuffix;
  }

  /**
   * Set the viewLocation of this {@link ConfigurationDocumentFullDetails} instance and return the
   * same instance.
   *
   * @param viewLocation View location of the document.
   * @return The same instance of this {@link ConfigurationDocumentFullDetails} class
   */
  @Nonnull
  public ConfigurationDocumentFullDetails viewLocation(@Nullable final String viewLocation) {
    this.viewLocation = viewLocation;
    return this;
  }

  /**
   * View location of the document.
   *
   * @return viewLocation The viewLocation of this {@link ConfigurationDocumentFullDetails}
   *     instance.
   */
  @Nonnull
  public String getViewLocation() {
    return viewLocation;
  }

  /**
   * Set the viewLocation of this {@link ConfigurationDocumentFullDetails} instance.
   *
   * @param viewLocation View location of the document.
   */
  public void setViewLocation(@Nullable final String viewLocation) {
    this.viewLocation = viewLocation;
  }

  /**
   * Set the downloadLocation of this {@link ConfigurationDocumentFullDetails} instance and return
   * the same instance.
   *
   * @param downloadLocation Download location of the document.
   * @return The same instance of this {@link ConfigurationDocumentFullDetails} class
   */
  @Nonnull
  public ConfigurationDocumentFullDetails downloadLocation(
      @Nullable final String downloadLocation) {
    this.downloadLocation = downloadLocation;
    return this;
  }

  /**
   * Download location of the document.
   *
   * @return downloadLocation The downloadLocation of this {@link ConfigurationDocumentFullDetails}
   *     instance.
   */
  @Nonnull
  public String getDownloadLocation() {
    return downloadLocation;
  }

  /**
   * Set the downloadLocation of this {@link ConfigurationDocumentFullDetails} instance.
   *
   * @param downloadLocation Download location of the document.
   */
  public void setDownloadLocation(@Nullable final String downloadLocation) {
    this.downloadLocation = downloadLocation;
  }

  /**
   * Set the mimeType of this {@link ConfigurationDocumentFullDetails} instance and return the same
   * instance.
   *
   * @param mimeType MIME type of the document.
   * @return The same instance of this {@link ConfigurationDocumentFullDetails} class
   */
  @Nonnull
  public ConfigurationDocumentFullDetails mimeType(@Nullable final String mimeType) {
    this.mimeType = mimeType;
    return this;
  }

  /**
   * MIME type of the document.
   *
   * @return mimeType The mimeType of this {@link ConfigurationDocumentFullDetails} instance.
   */
  @Nonnull
  public String getMimeType() {
    return mimeType;
  }

  /**
   * Set the mimeType of this {@link ConfigurationDocumentFullDetails} instance.
   *
   * @param mimeType MIME type of the document.
   */
  public void setMimeType(@Nullable final String mimeType) {
    this.mimeType = mimeType;
  }

  /**
   * Set the fileSizeMb of this {@link ConfigurationDocumentFullDetails} instance and return the
   * same instance.
   *
   * @param fileSizeMb File size of the document in megabytes.
   * @return The same instance of this {@link ConfigurationDocumentFullDetails} class
   */
  @Nonnull
  public ConfigurationDocumentFullDetails fileSizeMb(@Nullable final String fileSizeMb) {
    this.fileSizeMb = fileSizeMb;
    return this;
  }

  /**
   * File size of the document in megabytes.
   *
   * @return fileSizeMb The fileSizeMb of this {@link ConfigurationDocumentFullDetails} instance.
   */
  @Nonnull
  public String getFileSizeMb() {
    return fileSizeMb;
  }

  /**
   * Set the fileSizeMb of this {@link ConfigurationDocumentFullDetails} instance.
   *
   * @param fileSizeMb File size of the document in megabytes.
   */
  public void setFileSizeMb(@Nullable final String fileSizeMb) {
    this.fileSizeMb = fileSizeMb;
  }

  /**
   * Set the metadata of this {@link ConfigurationDocumentFullDetails} instance and return the same
   * instance.
   *
   * @param metadata Metadata key-value pairs associated with the document.
   * @return The same instance of this {@link ConfigurationDocumentFullDetails} class
   */
  @Nonnull
  public ConfigurationDocumentFullDetails metadata(
      @Nullable final List<DocumentMetadata> metadata) {
    this.metadata = metadata;
    return this;
  }

  /**
   * Add one metadata instance to this {@link ConfigurationDocumentFullDetails}.
   *
   * @param metadataItem The metadata that should be added
   * @return The same instance of type {@link ConfigurationDocumentFullDetails}
   */
  @Nonnull
  public ConfigurationDocumentFullDetails addMetadataItem(
      @Nonnull final DocumentMetadata metadataItem) {
    if (this.metadata == null) {
      this.metadata = new ArrayList<>();
    }
    this.metadata.add(metadataItem);
    return this;
  }

  /**
   * Metadata key-value pairs associated with the document.
   *
   * @return metadata The metadata of this {@link ConfigurationDocumentFullDetails} instance.
   */
  @Nonnull
  public List<DocumentMetadata> getMetadata() {
    return metadata;
  }

  /**
   * Set the metadata of this {@link ConfigurationDocumentFullDetails} instance.
   *
   * @param metadata Metadata key-value pairs associated with the document.
   */
  public void setMetadata(@Nullable final List<DocumentMetadata> metadata) {
    this.metadata = metadata;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link ConfigurationDocumentFullDetails}.
   *
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link ConfigurationDocumentFullDetails}
   * instance.
   *
   * @deprecated Use {@link #toMap()} instead.
   * @param name The name of the property
   * @return The value of the property
   * @throws NoSuchElementException If no property with the given name could be found.
   */
  @Nullable
  @Deprecated
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if (!cloudSdkCustomFields.containsKey(name)) {
      throw new NoSuchElementException(
          "ConfigurationDocumentFullDetails has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Get the value of all properties of this {@link ConfigurationDocumentFullDetails} instance
   * including unrecognized properties.
   *
   * @return The map of all properties
   */
  @JsonIgnore
  @Nonnull
  public Map<String, Object> toMap() {
    final Map<String, Object> declaredFields = new LinkedHashMap<>(cloudSdkCustomFields);
    if (id != null) declaredFields.put("id", id);
    if (title != null) declaredFields.put("title", title);
    if (absoluteFilePath != null) declaredFields.put("absoluteFilePath", absoluteFilePath);
    if (createdTimestamp != null) declaredFields.put("createdTimestamp", createdTimestamp);
    if (resourceUri != null) declaredFields.put("resourceUri", resourceUri);
    if (webUrl != null) declaredFields.put("webUrl", webUrl);
    if (documentEtag != null) declaredFields.put("documentEtag", documentEtag);
    if (fileSuffix != null) declaredFields.put("fileSuffix", fileSuffix);
    if (viewLocation != null) declaredFields.put("viewLocation", viewLocation);
    if (downloadLocation != null) declaredFields.put("downloadLocation", downloadLocation);
    if (mimeType != null) declaredFields.put("mimeType", mimeType);
    if (fileSizeMb != null) declaredFields.put("fileSizeMb", fileSizeMb);
    if (metadata != null) declaredFields.put("metadata", metadata);
    return declaredFields;
  }

  /**
   * Set an unrecognizable property of this {@link ConfigurationDocumentFullDetails} instance. If
   * the map previously contained a mapping for the key, the old value is replaced by the specified
   * value.
   *
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField(@Nonnull String customFieldName, @Nullable Object customFieldValue) {
    cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }

  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final ConfigurationDocumentFullDetails configurationDocumentFullDetails =
        (ConfigurationDocumentFullDetails) o;
    return Objects.equals(
            this.cloudSdkCustomFields, configurationDocumentFullDetails.cloudSdkCustomFields)
        && Objects.equals(this.id, configurationDocumentFullDetails.id)
        && Objects.equals(this.title, configurationDocumentFullDetails.title)
        && Objects.equals(this.absoluteFilePath, configurationDocumentFullDetails.absoluteFilePath)
        && Objects.equals(this.createdTimestamp, configurationDocumentFullDetails.createdTimestamp)
        && Objects.equals(this.resourceUri, configurationDocumentFullDetails.resourceUri)
        && Objects.equals(this.webUrl, configurationDocumentFullDetails.webUrl)
        && Objects.equals(this.documentEtag, configurationDocumentFullDetails.documentEtag)
        && Objects.equals(this.fileSuffix, configurationDocumentFullDetails.fileSuffix)
        && Objects.equals(this.viewLocation, configurationDocumentFullDetails.viewLocation)
        && Objects.equals(this.downloadLocation, configurationDocumentFullDetails.downloadLocation)
        && Objects.equals(this.mimeType, configurationDocumentFullDetails.mimeType)
        && Objects.equals(this.fileSizeMb, configurationDocumentFullDetails.fileSizeMb)
        && Objects.equals(this.metadata, configurationDocumentFullDetails.metadata);
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        id,
        title,
        absoluteFilePath,
        createdTimestamp,
        resourceUri,
        webUrl,
        documentEtag,
        fileSuffix,
        viewLocation,
        downloadLocation,
        mimeType,
        fileSizeMb,
        metadata,
        cloudSdkCustomFields);
  }

  @Override
  @Nonnull
  public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class ConfigurationDocumentFullDetails {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    absoluteFilePath: ").append(toIndentedString(absoluteFilePath)).append("\n");
    sb.append("    createdTimestamp: ").append(toIndentedString(createdTimestamp)).append("\n");
    sb.append("    resourceUri: ").append(toIndentedString(resourceUri)).append("\n");
    sb.append("    webUrl: ").append(toIndentedString(webUrl)).append("\n");
    sb.append("    documentEtag: ").append(toIndentedString(documentEtag)).append("\n");
    sb.append("    fileSuffix: ").append(toIndentedString(fileSuffix)).append("\n");
    sb.append("    viewLocation: ").append(toIndentedString(viewLocation)).append("\n");
    sb.append("    downloadLocation: ").append(toIndentedString(downloadLocation)).append("\n");
    sb.append("    mimeType: ").append(toIndentedString(mimeType)).append("\n");
    sb.append("    fileSizeMb: ").append(toIndentedString(fileSizeMb)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    cloudSdkCustomFields.forEach(
        (k, v) ->
            sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /** Create a new {@link ConfigurationDocumentFullDetails} instance. No arguments are required. */
  public static ConfigurationDocumentFullDetails create() {
    return new ConfigurationDocumentFullDetails();
  }
}
