/*
 * Grounding
 * Grounding is a service designed to handle data-related tasks, such as grounding and retrieval, using vector databases. It provides specialized data retrieval through these databases, grounding the retrieval process with your own external and context-relevant data. Grounding combines generative AI capabilities with the ability to use real-time, precise data to improve decision-making and business operations for specific AI-driven business solutions.
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.ai.sdk.grounding.model;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/** DocumentMetadataUpdateError */
// CHECKSTYLE:OFF
public class DocumentMetadataUpdateError implements BatchUpdateDocumentsResponseResultsInner
// CHECKSTYLE:ON
{
  @JsonProperty("target")
  private String target;

  @JsonProperty("code")
  private Integer code;

  @JsonProperty("message")
  private String message;

  @JsonAnySetter @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

  /** Default constructor for DocumentMetadataUpdateError. */
  protected DocumentMetadataUpdateError() {}

  /**
   * Set the target of this {@link DocumentMetadataUpdateError} instance and return the same
   * instance.
   *
   * @param target Document ID that caused the error.
   * @return The same instance of this {@link DocumentMetadataUpdateError} class
   */
  @Nonnull
  public DocumentMetadataUpdateError target(@Nonnull final String target) {
    this.target = target;
    return this;
  }

  /**
   * Document ID that caused the error.
   *
   * @return target The target of this {@link DocumentMetadataUpdateError} instance.
   */
  @Nonnull
  public String getTarget() {
    return target;
  }

  /**
   * Set the target of this {@link DocumentMetadataUpdateError} instance.
   *
   * @param target Document ID that caused the error.
   */
  public void setTarget(@Nonnull final String target) {
    this.target = target;
  }

  /**
   * Set the code of this {@link DocumentMetadataUpdateError} instance and return the same instance.
   *
   * @param code HTTP error status code.
   * @return The same instance of this {@link DocumentMetadataUpdateError} class
   */
  @Nonnull
  public DocumentMetadataUpdateError code(@Nonnull final Integer code) {
    this.code = code;
    return this;
  }

  /**
   * HTTP error status code.
   *
   * @return code The code of this {@link DocumentMetadataUpdateError} instance.
   */
  @Nonnull
  public Integer getCode() {
    return code;
  }

  /**
   * Set the code of this {@link DocumentMetadataUpdateError} instance.
   *
   * @param code HTTP error status code.
   */
  public void setCode(@Nonnull final Integer code) {
    this.code = code;
  }

  /**
   * Set the message of this {@link DocumentMetadataUpdateError} instance and return the same
   * instance.
   *
   * @param message Error message.
   * @return The same instance of this {@link DocumentMetadataUpdateError} class
   */
  @Nonnull
  public DocumentMetadataUpdateError message(@Nonnull final String message) {
    this.message = message;
    return this;
  }

  /**
   * Error message.
   *
   * @return message The message of this {@link DocumentMetadataUpdateError} instance.
   */
  @Nonnull
  public String getMessage() {
    return message;
  }

  /**
   * Set the message of this {@link DocumentMetadataUpdateError} instance.
   *
   * @param message Error message.
   */
  public void setMessage(@Nonnull final String message) {
    this.message = message;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link DocumentMetadataUpdateError}.
   *
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link DocumentMetadataUpdateError}
   * instance.
   *
   * @deprecated Use {@link #toMap()} instead.
   * @param name The name of the property
   * @return The value of the property
   * @throws NoSuchElementException If no property with the given name could be found.
   */
  @Nullable
  @Deprecated
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if (!cloudSdkCustomFields.containsKey(name)) {
      throw new NoSuchElementException(
          "DocumentMetadataUpdateError has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Get the value of all properties of this {@link DocumentMetadataUpdateError} instance including
   * unrecognized properties.
   *
   * @return The map of all properties
   */
  @JsonIgnore
  @Nonnull
  public Map<String, Object> toMap() {
    final Map<String, Object> declaredFields = new LinkedHashMap<>(cloudSdkCustomFields);
    if (target != null) declaredFields.put("target", target);
    if (code != null) declaredFields.put("code", code);
    if (message != null) declaredFields.put("message", message);
    return declaredFields;
  }

  /**
   * Set an unrecognizable property of this {@link DocumentMetadataUpdateError} instance. If the map
   * previously contained a mapping for the key, the old value is replaced by the specified value.
   *
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField(@Nonnull String customFieldName, @Nullable Object customFieldValue) {
    cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }

  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final DocumentMetadataUpdateError documentMetadataUpdateError = (DocumentMetadataUpdateError) o;
    return Objects.equals(
            this.cloudSdkCustomFields, documentMetadataUpdateError.cloudSdkCustomFields)
        && Objects.equals(this.target, documentMetadataUpdateError.target)
        && Objects.equals(this.code, documentMetadataUpdateError.code)
        && Objects.equals(this.message, documentMetadataUpdateError.message);
  }

  @Override
  public int hashCode() {
    return Objects.hash(target, code, message, cloudSdkCustomFields);
  }

  @Override
  @Nonnull
  public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class DocumentMetadataUpdateError {\n");
    sb.append("    target: ").append(toIndentedString(target)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    cloudSdkCustomFields.forEach(
        (k, v) ->
            sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Create a type-safe, fluent-api builder object to construct a new {@link
   * DocumentMetadataUpdateError} instance with all required arguments.
   */
  public static Builder create() {
    return (target) ->
        (code) ->
            (message) ->
                new DocumentMetadataUpdateError().target(target).code(code).message(message);
  }

  /** Builder helper class. */
  public interface Builder {
    /**
     * Set the target of this {@link DocumentMetadataUpdateError} instance.
     *
     * @param target Document ID that caused the error.
     * @return The DocumentMetadataUpdateError builder.
     */
    Builder1 target(@Nonnull final String target);
  }

  /** Builder helper class. */
  public interface Builder1 {
    /**
     * Set the code of this {@link DocumentMetadataUpdateError} instance.
     *
     * @param code HTTP error status code.
     * @return The DocumentMetadataUpdateError builder.
     */
    Builder2 code(@Nonnull final Integer code);
  }

  /** Builder helper class. */
  public interface Builder2 {
    /**
     * Set the message of this {@link DocumentMetadataUpdateError} instance.
     *
     * @param message Error message.
     * @return The DocumentMetadataUpdateError instance.
     */
    DocumentMetadataUpdateError message(@Nonnull final String message);
  }
}
