/*
 * Grounding
 * Grounding is a service designed to handle data-related tasks, such as grounding and retrieval, using vector databases. It provides specialized data retrieval through these databases, grounding the retrieval process with your own external and context-relevant data. Grounding combines generative AI capabilities with the ability to use real-time, precise data to improve decision-making and business operations for specific AI-driven business solutions.
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.ai.sdk.grounding.model;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/** GoogleDrivePipelineMinimalResponse */
// CHECKSTYLE:OFF
public class GoogleDrivePipelineMinimalResponse implements PipelineMinimalResponse
// CHECKSTYLE:ON
{
  @JsonProperty("id")
  private String id;

  @JsonProperty("status")
  private PipelineExecutionStatus status;

  /** Gets or Sets type */
  public enum TypeEnum {
    /** The GOOGLE_DRIVE option of this GoogleDrivePipelineMinimalResponse */
    GOOGLE_DRIVE("GoogleDrive"),

    /** The UNKNOWN_DEFAULT_OPEN_API option of this GoogleDrivePipelineMinimalResponse */
    UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    /**
     * Get the value of the enum
     *
     * @return The enum value
     */
    @JsonValue
    @Nonnull
    public String getValue() {
      return value;
    }

    /**
     * Get the String value of the enum value.
     *
     * @return The enum value as String
     */
    @Override
    @Nonnull
    public String toString() {
      return String.valueOf(value);
    }

    /**
     * Get the enum value from a String value
     *
     * @param value The String value
     * @return The enum value of type GoogleDrivePipelineMinimalResponse
     */
    @JsonCreator
    @Nonnull
    public static TypeEnum fromValue(@Nonnull final String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return UNKNOWN_DEFAULT_OPEN_API;
    }
  }

  @JsonProperty("type")
  private TypeEnum type;

  @JsonProperty("configuration")
  private GoogleDriveConfigurationMinimal _configuration;

  @JsonProperty("metadata")
  private Boolean metadata;

  @JsonAnySetter @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

  /** Default constructor for GoogleDrivePipelineMinimalResponse. */
  protected GoogleDrivePipelineMinimalResponse() {}

  /**
   * Set the id of this {@link GoogleDrivePipelineMinimalResponse} instance and return the same
   * instance.
   *
   * @param id The id of this {@link GoogleDrivePipelineMinimalResponse}
   * @return The same instance of this {@link GoogleDrivePipelineMinimalResponse} class
   */
  @Nonnull
  public GoogleDrivePipelineMinimalResponse id(@Nonnull final String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   *
   * @return id The id of this {@link GoogleDrivePipelineMinimalResponse} instance.
   */
  @Nonnull
  public String getId() {
    return id;
  }

  /**
   * Set the id of this {@link GoogleDrivePipelineMinimalResponse} instance.
   *
   * @param id The id of this {@link GoogleDrivePipelineMinimalResponse}
   */
  public void setId(@Nonnull final String id) {
    this.id = id;
  }

  /**
   * Set the status of this {@link GoogleDrivePipelineMinimalResponse} instance and return the same
   * instance.
   *
   * @param status The status of this {@link GoogleDrivePipelineMinimalResponse}
   * @return The same instance of this {@link GoogleDrivePipelineMinimalResponse} class
   */
  @Nonnull
  public GoogleDrivePipelineMinimalResponse status(@Nullable final PipelineExecutionStatus status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   *
   * @return status The status of this {@link GoogleDrivePipelineMinimalResponse} instance.
   */
  @Nullable
  public PipelineExecutionStatus getStatus() {
    return status;
  }

  /**
   * Set the status of this {@link GoogleDrivePipelineMinimalResponse} instance.
   *
   * @param status The status of this {@link GoogleDrivePipelineMinimalResponse}
   */
  public void setStatus(@Nullable final PipelineExecutionStatus status) {
    this.status = status;
  }

  /**
   * Set the type of this {@link GoogleDrivePipelineMinimalResponse} instance and return the same
   * instance.
   *
   * @param type The type of this {@link GoogleDrivePipelineMinimalResponse}
   * @return The same instance of this {@link GoogleDrivePipelineMinimalResponse} class
   */
  @Nonnull
  public GoogleDrivePipelineMinimalResponse type(@Nonnull final TypeEnum type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   *
   * @return type The type of this {@link GoogleDrivePipelineMinimalResponse} instance.
   */
  @Nonnull
  public TypeEnum getType() {
    return type;
  }

  /**
   * Set the type of this {@link GoogleDrivePipelineMinimalResponse} instance.
   *
   * @param type The type of this {@link GoogleDrivePipelineMinimalResponse}
   */
  public void setType(@Nonnull final TypeEnum type) {
    this.type = type;
  }

  /**
   * Set the _configuration of this {@link GoogleDrivePipelineMinimalResponse} instance and return
   * the same instance.
   *
   * @param _configuration The _configuration of this {@link GoogleDrivePipelineMinimalResponse}
   * @return The same instance of this {@link GoogleDrivePipelineMinimalResponse} class
   */
  @Nonnull
  public GoogleDrivePipelineMinimalResponse _configuration(
      @Nullable final GoogleDriveConfigurationMinimal _configuration) {
    this._configuration = _configuration;
    return this;
  }

  /**
   * Get _configuration
   *
   * @return _configuration The _configuration of this {@link GoogleDrivePipelineMinimalResponse}
   *     instance.
   */
  @Nonnull
  public GoogleDriveConfigurationMinimal getConfiguration() {
    return _configuration;
  }

  /**
   * Set the _configuration of this {@link GoogleDrivePipelineMinimalResponse} instance.
   *
   * @param _configuration The _configuration of this {@link GoogleDrivePipelineMinimalResponse}
   */
  public void setConfiguration(@Nullable final GoogleDriveConfigurationMinimal _configuration) {
    this._configuration = _configuration;
  }

  /**
   * Set the metadata of this {@link GoogleDrivePipelineMinimalResponse} instance and return the
   * same instance.
   *
   * @param metadata The metadata of this {@link GoogleDrivePipelineMinimalResponse}
   * @return The same instance of this {@link GoogleDrivePipelineMinimalResponse} class
   */
  @Nonnull
  public GoogleDrivePipelineMinimalResponse metadata(@Nullable final Boolean metadata) {
    this.metadata = metadata;
    return this;
  }

  /**
   * Get metadata
   *
   * @return metadata The metadata of this {@link GoogleDrivePipelineMinimalResponse} instance.
   */
  @Nonnull
  public Boolean isMetadata() {
    return metadata;
  }

  /**
   * Set the metadata of this {@link GoogleDrivePipelineMinimalResponse} instance.
   *
   * @param metadata The metadata of this {@link GoogleDrivePipelineMinimalResponse}
   */
  public void setMetadata(@Nullable final Boolean metadata) {
    this.metadata = metadata;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link
   * GoogleDrivePipelineMinimalResponse}.
   *
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link GoogleDrivePipelineMinimalResponse}
   * instance.
   *
   * @deprecated Use {@link #toMap()} instead.
   * @param name The name of the property
   * @return The value of the property
   * @throws NoSuchElementException If no property with the given name could be found.
   */
  @Nullable
  @Deprecated
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if (!cloudSdkCustomFields.containsKey(name)) {
      throw new NoSuchElementException(
          "GoogleDrivePipelineMinimalResponse has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Get the value of all properties of this {@link GoogleDrivePipelineMinimalResponse} instance
   * including unrecognized properties.
   *
   * @return The map of all properties
   */
  @JsonIgnore
  @Nonnull
  public Map<String, Object> toMap() {
    final Map<String, Object> declaredFields = new LinkedHashMap<>(cloudSdkCustomFields);
    if (id != null) declaredFields.put("id", id);
    if (status != null) declaredFields.put("status", status);
    if (type != null) declaredFields.put("type", type);
    if (_configuration != null) declaredFields.put("_configuration", _configuration);
    if (metadata != null) declaredFields.put("metadata", metadata);
    return declaredFields;
  }

  /**
   * Set an unrecognizable property of this {@link GoogleDrivePipelineMinimalResponse} instance. If
   * the map previously contained a mapping for the key, the old value is replaced by the specified
   * value.
   *
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField(@Nonnull String customFieldName, @Nullable Object customFieldValue) {
    cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }

  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final GoogleDrivePipelineMinimalResponse googleDrivePipelineMinimalResponse =
        (GoogleDrivePipelineMinimalResponse) o;
    return Objects.equals(
            this.cloudSdkCustomFields, googleDrivePipelineMinimalResponse.cloudSdkCustomFields)
        && Objects.equals(this.id, googleDrivePipelineMinimalResponse.id)
        && Objects.equals(this.status, googleDrivePipelineMinimalResponse.status)
        && Objects.equals(this.type, googleDrivePipelineMinimalResponse.type)
        && Objects.equals(this._configuration, googleDrivePipelineMinimalResponse._configuration)
        && Objects.equals(this.metadata, googleDrivePipelineMinimalResponse.metadata);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, status, type, _configuration, metadata, cloudSdkCustomFields);
  }

  @Override
  @Nonnull
  public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class GoogleDrivePipelineMinimalResponse {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    _configuration: ").append(toIndentedString(_configuration)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    cloudSdkCustomFields.forEach(
        (k, v) ->
            sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Create a type-safe, fluent-api builder object to construct a new {@link
   * GoogleDrivePipelineMinimalResponse} instance with all required arguments.
   */
  public static Builder create() {
    return (id) ->
        (status) ->
            (type) -> new GoogleDrivePipelineMinimalResponse().id(id).status(status).type(type);
  }

  /** Builder helper class. */
  public interface Builder {
    /**
     * Set the id of this {@link GoogleDrivePipelineMinimalResponse} instance.
     *
     * @param id The id of this {@link GoogleDrivePipelineMinimalResponse}
     * @return The GoogleDrivePipelineMinimalResponse builder.
     */
    Builder1 id(@Nonnull final String id);
  }

  /** Builder helper class. */
  public interface Builder1 {
    /**
     * Set the status of this {@link GoogleDrivePipelineMinimalResponse} instance.
     *
     * @param status The status of this {@link GoogleDrivePipelineMinimalResponse}
     * @return The GoogleDrivePipelineMinimalResponse builder.
     */
    Builder2 status(@Nullable final PipelineExecutionStatus status);
  }

  /** Builder helper class. */
  public interface Builder2 {
    /**
     * Set the type of this {@link GoogleDrivePipelineMinimalResponse} instance.
     *
     * @param type The type of this {@link GoogleDrivePipelineMinimalResponse}
     * @return The GoogleDrivePipelineMinimalResponse instance.
     */
    GoogleDrivePipelineMinimalResponse type(@Nonnull final TypeEnum type);
  }
}
