/*
 * Grounding
 * Grounding is a service designed to handle data-related tasks, such as grounding and retrieval, using vector databases. It provides specialized data retrieval through these databases, grounding the retrieval process with your own external and context-relevant data. Grounding combines generative AI capabilities with the ability to use real-time, precise data to improve decision-making and business operations for specific AI-driven business solutions.
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.ai.sdk.grounding.model;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/** ListConfigurationDocumentsFullDetails */
// CHECKSTYLE:OFF
public class ListConfigurationDocumentsFullDetails
// CHECKSTYLE:ON
{
  @JsonProperty("count")
  private Integer count;

  @JsonProperty("resources")
  private List<ConfigurationDocumentFullDetails> resources = new ArrayList<>();

  @JsonAnySetter @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

  /** Default constructor for ListConfigurationDocumentsFullDetails. */
  protected ListConfigurationDocumentsFullDetails() {}

  /**
   * Set the count of this {@link ListConfigurationDocumentsFullDetails} instance and return the
   * same instance.
   *
   * @param count Total number of documents returned.
   * @return The same instance of this {@link ListConfigurationDocumentsFullDetails} class
   */
  @Nonnull
  public ListConfigurationDocumentsFullDetails count(@Nullable final Integer count) {
    this.count = count;
    return this;
  }

  /**
   * Total number of documents returned.
   *
   * @return count The count of this {@link ListConfigurationDocumentsFullDetails} instance.
   */
  @Nonnull
  public Integer getCount() {
    return count;
  }

  /**
   * Set the count of this {@link ListConfigurationDocumentsFullDetails} instance.
   *
   * @param count Total number of documents returned.
   */
  public void setCount(@Nullable final Integer count) {
    this.count = count;
  }

  /**
   * Set the resources of this {@link ListConfigurationDocumentsFullDetails} instance and return the
   * same instance.
   *
   * @param resources List of document objects. It will be empty array if no records found.
   * @return The same instance of this {@link ListConfigurationDocumentsFullDetails} class
   */
  @Nonnull
  public ListConfigurationDocumentsFullDetails resources(
      @Nullable final List<ConfigurationDocumentFullDetails> resources) {
    this.resources = resources;
    return this;
  }

  /**
   * Add one resources instance to this {@link ListConfigurationDocumentsFullDetails}.
   *
   * @param resourcesItem The resources that should be added
   * @return The same instance of type {@link ListConfigurationDocumentsFullDetails}
   */
  @Nonnull
  public ListConfigurationDocumentsFullDetails addResourcesItem(
      @Nonnull final ConfigurationDocumentFullDetails resourcesItem) {
    if (this.resources == null) {
      this.resources = new ArrayList<>();
    }
    this.resources.add(resourcesItem);
    return this;
  }

  /**
   * List of document objects. It will be empty array if no records found.
   *
   * @return resources The resources of this {@link ListConfigurationDocumentsFullDetails} instance.
   */
  @Nonnull
  public List<ConfigurationDocumentFullDetails> getResources() {
    return resources;
  }

  /**
   * Set the resources of this {@link ListConfigurationDocumentsFullDetails} instance.
   *
   * @param resources List of document objects. It will be empty array if no records found.
   */
  public void setResources(@Nullable final List<ConfigurationDocumentFullDetails> resources) {
    this.resources = resources;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link
   * ListConfigurationDocumentsFullDetails}.
   *
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link
   * ListConfigurationDocumentsFullDetails} instance.
   *
   * @deprecated Use {@link #toMap()} instead.
   * @param name The name of the property
   * @return The value of the property
   * @throws NoSuchElementException If no property with the given name could be found.
   */
  @Nullable
  @Deprecated
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if (!cloudSdkCustomFields.containsKey(name)) {
      throw new NoSuchElementException(
          "ListConfigurationDocumentsFullDetails has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Get the value of all properties of this {@link ListConfigurationDocumentsFullDetails} instance
   * including unrecognized properties.
   *
   * @return The map of all properties
   */
  @JsonIgnore
  @Nonnull
  public Map<String, Object> toMap() {
    final Map<String, Object> declaredFields = new LinkedHashMap<>(cloudSdkCustomFields);
    if (count != null) declaredFields.put("count", count);
    if (resources != null) declaredFields.put("resources", resources);
    return declaredFields;
  }

  /**
   * Set an unrecognizable property of this {@link ListConfigurationDocumentsFullDetails} instance.
   * If the map previously contained a mapping for the key, the old value is replaced by the
   * specified value.
   *
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField(@Nonnull String customFieldName, @Nullable Object customFieldValue) {
    cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }

  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final ListConfigurationDocumentsFullDetails listConfigurationDocumentsFullDetails =
        (ListConfigurationDocumentsFullDetails) o;
    return Objects.equals(
            this.cloudSdkCustomFields, listConfigurationDocumentsFullDetails.cloudSdkCustomFields)
        && Objects.equals(this.count, listConfigurationDocumentsFullDetails.count)
        && Objects.equals(this.resources, listConfigurationDocumentsFullDetails.resources);
  }

  @Override
  public int hashCode() {
    return Objects.hash(count, resources, cloudSdkCustomFields);
  }

  @Override
  @Nonnull
  public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class ListConfigurationDocumentsFullDetails {\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    resources: ").append(toIndentedString(resources)).append("\n");
    cloudSdkCustomFields.forEach(
        (k, v) ->
            sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Create a new {@link ListConfigurationDocumentsFullDetails} instance. No arguments are required.
   */
  public static ListConfigurationDocumentsFullDetails create() {
    return new ListConfigurationDocumentsFullDetails();
  }
}
