/*
 * Grounding
 * Grounding is a service designed to handle data-related tasks, such as grounding and retrieval, using vector databases. It provides specialized data retrieval through these databases, grounding the retrieval process with your own external and context-relevant data. Grounding combines generative AI capabilities with the ability to use real-time, precise data to improve decision-making and business operations for specific AI-driven business solutions.
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.ai.sdk.grounding.model;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/** MetadataUpdates */
// CHECKSTYLE:OFF
public class MetadataUpdates
// CHECKSTYLE:ON
{
  @JsonProperty("updates")
  private List<MetadataUpdateItem> updates = new ArrayList<>();

  @JsonAnySetter @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

  /** Default constructor for MetadataUpdates. */
  protected MetadataUpdates() {}

  /**
   * Set the updates of this {@link MetadataUpdates} instance and return the same instance.
   *
   * @param updates List of metadata updates.
   * @return The same instance of this {@link MetadataUpdates} class
   */
  @Nonnull
  public MetadataUpdates updates(@Nonnull final List<MetadataUpdateItem> updates) {
    this.updates = updates;
    return this;
  }

  /**
   * Add one updates instance to this {@link MetadataUpdates}.
   *
   * @param updatesItem The updates that should be added
   * @return The same instance of type {@link MetadataUpdates}
   */
  @Nonnull
  public MetadataUpdates addUpdatesItem(@Nonnull final MetadataUpdateItem updatesItem) {
    if (this.updates == null) {
      this.updates = new ArrayList<>();
    }
    this.updates.add(updatesItem);
    return this;
  }

  /**
   * List of metadata updates.
   *
   * @return updates The updates of this {@link MetadataUpdates} instance.
   */
  @Nonnull
  public List<MetadataUpdateItem> getUpdates() {
    return updates;
  }

  /**
   * Set the updates of this {@link MetadataUpdates} instance.
   *
   * @param updates List of metadata updates.
   */
  public void setUpdates(@Nonnull final List<MetadataUpdateItem> updates) {
    this.updates = updates;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link MetadataUpdates}.
   *
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link MetadataUpdates} instance.
   *
   * @deprecated Use {@link #toMap()} instead.
   * @param name The name of the property
   * @return The value of the property
   * @throws NoSuchElementException If no property with the given name could be found.
   */
  @Nullable
  @Deprecated
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if (!cloudSdkCustomFields.containsKey(name)) {
      throw new NoSuchElementException("MetadataUpdates has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Get the value of all properties of this {@link MetadataUpdates} instance including unrecognized
   * properties.
   *
   * @return The map of all properties
   */
  @JsonIgnore
  @Nonnull
  public Map<String, Object> toMap() {
    final Map<String, Object> declaredFields = new LinkedHashMap<>(cloudSdkCustomFields);
    if (updates != null) declaredFields.put("updates", updates);
    return declaredFields;
  }

  /**
   * Set an unrecognizable property of this {@link MetadataUpdates} instance. If the map previously
   * contained a mapping for the key, the old value is replaced by the specified value.
   *
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField(@Nonnull String customFieldName, @Nullable Object customFieldValue) {
    cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }

  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final MetadataUpdates metadataUpdates = (MetadataUpdates) o;
    return Objects.equals(this.cloudSdkCustomFields, metadataUpdates.cloudSdkCustomFields)
        && Objects.equals(this.updates, metadataUpdates.updates);
  }

  @Override
  public int hashCode() {
    return Objects.hash(updates, cloudSdkCustomFields);
  }

  @Override
  @Nonnull
  public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class MetadataUpdates {\n");
    sb.append("    updates: ").append(toIndentedString(updates)).append("\n");
    cloudSdkCustomFields.forEach(
        (k, v) ->
            sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Create a type-safe, fluent-api builder object to construct a new {@link MetadataUpdates}
   * instance with all required arguments.
   */
  public static Builder create() {
    return (updates) -> new MetadataUpdates().updates(updates);
  }

  /** Builder helper class. */
  public interface Builder {
    /**
     * Set the updates of this {@link MetadataUpdates} instance.
     *
     * @param updates List of metadata updates.
     * @return The MetadataUpdates instance.
     */
    MetadataUpdates updates(@Nonnull final List<MetadataUpdateItem> updates);

    /**
     * Set the updates of this {@link MetadataUpdates} instance.
     *
     * @param updates List of metadata updates.
     * @return The MetadataUpdates instance.
     */
    default MetadataUpdates updates(@Nonnull final MetadataUpdateItem... updates) {
      return updates(Arrays.asList(updates));
    }
  }
}
