/*
 * Grounding
 * Grounding is a service designed to handle data-related tasks, such as grounding and retrieval, using vector databases. It provides specialized data retrieval through these databases, grounding the retrieval process with your own external and context-relevant data. Grounding combines generative AI capabilities with the ability to use real-time, precise data to improve decision-making and business operations for specific AI-driven business solutions.
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.ai.sdk.grounding.model;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/** PatchPipeline */
// CHECKSTYLE:OFF
public class PatchPipeline
// CHECKSTYLE:ON
{
  @JsonProperty("metadata")
  private PatchPipelineMetadata metadata;

  @JsonProperty("configuration")
  private PatchPipelineConfiguration _configuration;

  @JsonAnySetter @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

  /** Default constructor for PatchPipeline. */
  protected PatchPipeline() {}

  /**
   * Set the metadata of this {@link PatchPipeline} instance and return the same instance.
   *
   * @param metadata The metadata of this {@link PatchPipeline}
   * @return The same instance of this {@link PatchPipeline} class
   */
  @Nonnull
  public PatchPipeline metadata(@Nullable final PatchPipelineMetadata metadata) {
    this.metadata = metadata;
    return this;
  }

  /**
   * Get metadata
   *
   * @return metadata The metadata of this {@link PatchPipeline} instance.
   */
  @Nonnull
  public PatchPipelineMetadata getMetadata() {
    return metadata;
  }

  /**
   * Set the metadata of this {@link PatchPipeline} instance.
   *
   * @param metadata The metadata of this {@link PatchPipeline}
   */
  public void setMetadata(@Nullable final PatchPipelineMetadata metadata) {
    this.metadata = metadata;
  }

  /**
   * Set the _configuration of this {@link PatchPipeline} instance and return the same instance.
   *
   * @param _configuration The _configuration of this {@link PatchPipeline}
   * @return The same instance of this {@link PatchPipeline} class
   */
  @Nonnull
  public PatchPipeline _configuration(@Nullable final PatchPipelineConfiguration _configuration) {
    this._configuration = _configuration;
    return this;
  }

  /**
   * Get _configuration
   *
   * @return _configuration The _configuration of this {@link PatchPipeline} instance.
   */
  @Nonnull
  public PatchPipelineConfiguration getConfiguration() {
    return _configuration;
  }

  /**
   * Set the _configuration of this {@link PatchPipeline} instance.
   *
   * @param _configuration The _configuration of this {@link PatchPipeline}
   */
  public void setConfiguration(@Nullable final PatchPipelineConfiguration _configuration) {
    this._configuration = _configuration;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link PatchPipeline}.
   *
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link PatchPipeline} instance.
   *
   * @deprecated Use {@link #toMap()} instead.
   * @param name The name of the property
   * @return The value of the property
   * @throws NoSuchElementException If no property with the given name could be found.
   */
  @Nullable
  @Deprecated
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if (!cloudSdkCustomFields.containsKey(name)) {
      throw new NoSuchElementException("PatchPipeline has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Get the value of all properties of this {@link PatchPipeline} instance including unrecognized
   * properties.
   *
   * @return The map of all properties
   */
  @JsonIgnore
  @Nonnull
  public Map<String, Object> toMap() {
    final Map<String, Object> declaredFields = new LinkedHashMap<>(cloudSdkCustomFields);
    if (metadata != null) declaredFields.put("metadata", metadata);
    if (_configuration != null) declaredFields.put("_configuration", _configuration);
    return declaredFields;
  }

  /**
   * Set an unrecognizable property of this {@link PatchPipeline} instance. If the map previously
   * contained a mapping for the key, the old value is replaced by the specified value.
   *
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField(@Nonnull String customFieldName, @Nullable Object customFieldValue) {
    cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }

  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final PatchPipeline patchPipeline = (PatchPipeline) o;
    return Objects.equals(this.cloudSdkCustomFields, patchPipeline.cloudSdkCustomFields)
        && Objects.equals(this.metadata, patchPipeline.metadata)
        && Objects.equals(this._configuration, patchPipeline._configuration);
  }

  @Override
  public int hashCode() {
    return Objects.hash(metadata, _configuration, cloudSdkCustomFields);
  }

  @Override
  @Nonnull
  public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class PatchPipeline {\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    _configuration: ").append(toIndentedString(_configuration)).append("\n");
    cloudSdkCustomFields.forEach(
        (k, v) ->
            sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /** Create a new {@link PatchPipeline} instance. No arguments are required. */
  public static PatchPipeline create() {
    return new PatchPipeline();
  }
}
