/*
 * Grounding
 * Grounding is a service designed to handle data-related tasks, such as grounding and retrieval, using vector databases. It provides specialized data retrieval through these databases, grounding the retrieval process with your own external and context-relevant data. Grounding combines generative AI capabilities with the ability to use real-time, precise data to improve decision-making and business operations for specific AI-driven business solutions.
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.ai.sdk.grounding.model;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/** PostProcessingOperation */
// CHECKSTYLE:OFF
public class PostProcessingOperation implements RetrievalSearchInputPostProcessingInnerInputsInner
// CHECKSTYLE:ON
{
  @JsonProperty("id")
  private String id;

  @JsonProperty("maxChunkCount")
  private Integer maxChunkCount;

  @JsonProperty("strategy")
  private Strategy strategy;

  @JsonProperty("inputs")
  private List<RetrievalSearchInputPostProcessingInnerInputsInner> inputs = new ArrayList<>();

  @JsonAnySetter @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

  /** Default constructor for PostProcessingOperation. */
  protected PostProcessingOperation() {}

  /**
   * Set the id of this {@link PostProcessingOperation} instance and return the same instance.
   *
   * @param id The id of this {@link PostProcessingOperation}
   * @return The same instance of this {@link PostProcessingOperation} class
   */
  @Nonnull
  public PostProcessingOperation id(@Nullable final String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   *
   * @return id The id of this {@link PostProcessingOperation} instance.
   */
  @Nullable
  public String getId() {
    return id;
  }

  /**
   * Set the id of this {@link PostProcessingOperation} instance.
   *
   * @param id The id of this {@link PostProcessingOperation}
   */
  public void setId(@Nullable final String id) {
    this.id = id;
  }

  /**
   * Set the maxChunkCount of this {@link PostProcessingOperation} instance and return the same
   * instance.
   *
   * @param maxChunkCount The maxChunkCount of this {@link PostProcessingOperation} Maximum:
   *     10000000
   * @return The same instance of this {@link PostProcessingOperation} class
   */
  @Nonnull
  public PostProcessingOperation maxChunkCount(@Nullable final Integer maxChunkCount) {
    this.maxChunkCount = maxChunkCount;
    return this;
  }

  /**
   * Get maxChunkCount maximum: 10000000
   *
   * @return maxChunkCount The maxChunkCount of this {@link PostProcessingOperation} instance.
   */
  @Nullable
  public Integer getMaxChunkCount() {
    return maxChunkCount;
  }

  /**
   * Set the maxChunkCount of this {@link PostProcessingOperation} instance.
   *
   * @param maxChunkCount The maxChunkCount of this {@link PostProcessingOperation} Maximum:
   *     10000000
   */
  public void setMaxChunkCount(@Nullable final Integer maxChunkCount) {
    this.maxChunkCount = maxChunkCount;
  }

  /**
   * Set the strategy of this {@link PostProcessingOperation} instance and return the same instance.
   *
   * @param strategy The strategy of this {@link PostProcessingOperation}
   * @return The same instance of this {@link PostProcessingOperation} class
   */
  @Nonnull
  public PostProcessingOperation strategy(@Nonnull final Strategy strategy) {
    this.strategy = strategy;
    return this;
  }

  /**
   * Get strategy
   *
   * @return strategy The strategy of this {@link PostProcessingOperation} instance.
   */
  @Nonnull
  public Strategy getStrategy() {
    return strategy;
  }

  /**
   * Set the strategy of this {@link PostProcessingOperation} instance.
   *
   * @param strategy The strategy of this {@link PostProcessingOperation}
   */
  public void setStrategy(@Nonnull final Strategy strategy) {
    this.strategy = strategy;
  }

  /**
   * Set the inputs of this {@link PostProcessingOperation} instance and return the same instance.
   *
   * @param inputs The inputs of this {@link PostProcessingOperation}
   * @return The same instance of this {@link PostProcessingOperation} class
   */
  @Nonnull
  public PostProcessingOperation inputs(
      @Nonnull final List<RetrievalSearchInputPostProcessingInnerInputsInner> inputs) {
    this.inputs = inputs;
    return this;
  }

  /**
   * Add one inputs instance to this {@link PostProcessingOperation}.
   *
   * @param inputsItem The inputs that should be added
   * @return The same instance of type {@link PostProcessingOperation}
   */
  @Nonnull
  public PostProcessingOperation addInputsItem(
      @Nonnull final RetrievalSearchInputPostProcessingInnerInputsInner inputsItem) {
    if (this.inputs == null) {
      this.inputs = new ArrayList<>();
    }
    this.inputs.add(inputsItem);
    return this;
  }

  /**
   * Get inputs
   *
   * @return inputs The inputs of this {@link PostProcessingOperation} instance.
   */
  @Nonnull
  public List<RetrievalSearchInputPostProcessingInnerInputsInner> getInputs() {
    return inputs;
  }

  /**
   * Set the inputs of this {@link PostProcessingOperation} instance.
   *
   * @param inputs The inputs of this {@link PostProcessingOperation}
   */
  public void setInputs(
      @Nonnull final List<RetrievalSearchInputPostProcessingInnerInputsInner> inputs) {
    this.inputs = inputs;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link PostProcessingOperation}.
   *
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link PostProcessingOperation} instance.
   *
   * @deprecated Use {@link #toMap()} instead.
   * @param name The name of the property
   * @return The value of the property
   * @throws NoSuchElementException If no property with the given name could be found.
   */
  @Nullable
  @Deprecated
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if (!cloudSdkCustomFields.containsKey(name)) {
      throw new NoSuchElementException(
          "PostProcessingOperation has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Get the value of all properties of this {@link PostProcessingOperation} instance including
   * unrecognized properties.
   *
   * @return The map of all properties
   */
  @JsonIgnore
  @Nonnull
  public Map<String, Object> toMap() {
    final Map<String, Object> declaredFields = new LinkedHashMap<>(cloudSdkCustomFields);
    if (id != null) declaredFields.put("id", id);
    if (maxChunkCount != null) declaredFields.put("maxChunkCount", maxChunkCount);
    if (strategy != null) declaredFields.put("strategy", strategy);
    if (inputs != null) declaredFields.put("inputs", inputs);
    return declaredFields;
  }

  /**
   * Set an unrecognizable property of this {@link PostProcessingOperation} instance. If the map
   * previously contained a mapping for the key, the old value is replaced by the specified value.
   *
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField(@Nonnull String customFieldName, @Nullable Object customFieldValue) {
    cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }

  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final PostProcessingOperation postProcessingOperation = (PostProcessingOperation) o;
    return Objects.equals(this.cloudSdkCustomFields, postProcessingOperation.cloudSdkCustomFields)
        && Objects.equals(this.id, postProcessingOperation.id)
        && Objects.equals(this.maxChunkCount, postProcessingOperation.maxChunkCount)
        && Objects.equals(this.strategy, postProcessingOperation.strategy)
        && Objects.equals(this.inputs, postProcessingOperation.inputs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, maxChunkCount, strategy, inputs, cloudSdkCustomFields);
  }

  @Override
  @Nonnull
  public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class PostProcessingOperation {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    maxChunkCount: ").append(toIndentedString(maxChunkCount)).append("\n");
    sb.append("    strategy: ").append(toIndentedString(strategy)).append("\n");
    sb.append("    inputs: ").append(toIndentedString(inputs)).append("\n");
    cloudSdkCustomFields.forEach(
        (k, v) ->
            sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Create a type-safe, fluent-api builder object to construct a new {@link
   * PostProcessingOperation} instance with all required arguments.
   */
  public static Builder create() {
    return (strategy) ->
        (inputs) -> new PostProcessingOperation().strategy(strategy).inputs(inputs);
  }

  /** Builder helper class. */
  public interface Builder {
    /**
     * Set the strategy of this {@link PostProcessingOperation} instance.
     *
     * @param strategy The strategy of this {@link PostProcessingOperation}
     * @return The PostProcessingOperation builder.
     */
    Builder1 strategy(@Nonnull final Strategy strategy);
  }

  /** Builder helper class. */
  public interface Builder1 {
    /**
     * Set the inputs of this {@link PostProcessingOperation} instance.
     *
     * @param inputs The inputs of this {@link PostProcessingOperation}
     * @return The PostProcessingOperation instance.
     */
    PostProcessingOperation inputs(
        @Nonnull final List<RetrievalSearchInputPostProcessingInnerInputsInner> inputs);

    /**
     * Set the inputs of this {@link PostProcessingOperation} instance.
     *
     * @param inputs The inputs of this {@link PostProcessingOperation}
     * @return The PostProcessingOperation instance.
     */
    default PostProcessingOperation inputs(
        @Nonnull final RetrievalSearchInputPostProcessingInnerInputsInner... inputs) {
      return inputs(Arrays.asList(inputs));
    }
  }
}
