/*
 * Grounding
 * Grounding is a service designed to handle data-related tasks, such as grounding and retrieval, using vector databases. It provides specialized data retrieval through these databases, grounding the retrieval process with your own external and context-relevant data. Grounding combines generative AI capabilities with the ability to use real-time, precise data to improve decision-making and business operations for specific AI-driven business solutions.
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.ai.sdk.grounding.model;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/** PresignedUrlRequest */
// CHECKSTYLE:OFF
public class PresignedUrlRequest
// CHECKSTYLE:ON
{
  @JsonProperty("expirationSecs")
  private Integer expirationSecs;

  @JsonAnySetter @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

  /** Default constructor for PresignedUrlRequest. */
  protected PresignedUrlRequest() {}

  /**
   * Set the expirationSecs of this {@link PresignedUrlRequest} instance and return the same
   * instance.
   *
   * @param expirationSecs Expiration time in seconds for the presigned URL (600–604800). If
   *     omitted, the destination&#39;s presign_expiration_secs setting is used. Minimum: 600
   *     Maximum: 604800
   * @return The same instance of this {@link PresignedUrlRequest} class
   */
  @Nonnull
  public PresignedUrlRequest expirationSecs(@Nullable final Integer expirationSecs) {
    this.expirationSecs = expirationSecs;
    return this;
  }

  /**
   * Expiration time in seconds for the presigned URL (600–604800). If omitted, the
   * destination&#39;s presign_expiration_secs setting is used. minimum: 600 maximum: 604800
   *
   * @return expirationSecs The expirationSecs of this {@link PresignedUrlRequest} instance.
   */
  @Nonnull
  public Integer getExpirationSecs() {
    return expirationSecs;
  }

  /**
   * Set the expirationSecs of this {@link PresignedUrlRequest} instance.
   *
   * @param expirationSecs Expiration time in seconds for the presigned URL (600–604800). If
   *     omitted, the destination&#39;s presign_expiration_secs setting is used. Minimum: 600
   *     Maximum: 604800
   */
  public void setExpirationSecs(@Nullable final Integer expirationSecs) {
    this.expirationSecs = expirationSecs;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link PresignedUrlRequest}.
   *
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link PresignedUrlRequest} instance.
   *
   * @deprecated Use {@link #toMap()} instead.
   * @param name The name of the property
   * @return The value of the property
   * @throws NoSuchElementException If no property with the given name could be found.
   */
  @Nullable
  @Deprecated
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if (!cloudSdkCustomFields.containsKey(name)) {
      throw new NoSuchElementException(
          "PresignedUrlRequest has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Get the value of all properties of this {@link PresignedUrlRequest} instance including
   * unrecognized properties.
   *
   * @return The map of all properties
   */
  @JsonIgnore
  @Nonnull
  public Map<String, Object> toMap() {
    final Map<String, Object> declaredFields = new LinkedHashMap<>(cloudSdkCustomFields);
    if (expirationSecs != null) declaredFields.put("expirationSecs", expirationSecs);
    return declaredFields;
  }

  /**
   * Set an unrecognizable property of this {@link PresignedUrlRequest} instance. If the map
   * previously contained a mapping for the key, the old value is replaced by the specified value.
   *
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField(@Nonnull String customFieldName, @Nullable Object customFieldValue) {
    cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }

  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final PresignedUrlRequest presignedUrlRequest = (PresignedUrlRequest) o;
    return Objects.equals(this.cloudSdkCustomFields, presignedUrlRequest.cloudSdkCustomFields)
        && Objects.equals(this.expirationSecs, presignedUrlRequest.expirationSecs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(expirationSecs, cloudSdkCustomFields);
  }

  @Override
  @Nonnull
  public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class PresignedUrlRequest {\n");
    sb.append("    expirationSecs: ").append(toIndentedString(expirationSecs)).append("\n");
    cloudSdkCustomFields.forEach(
        (k, v) ->
            sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /** Create a new {@link PresignedUrlRequest} instance. No arguments are required. */
  public static PresignedUrlRequest create() {
    return new PresignedUrlRequest();
  }
}
