/*
 * Grounding
 * Grounding is a service designed to handle data-related tasks, such as grounding and retrieval, using vector databases. It provides specialized data retrieval through these databases, grounding the retrieval process with your own external and context-relevant data. Grounding combines generative AI capabilities with the ability to use real-time, precise data to improve decision-making and business operations for specific AI-driven business solutions.
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.ai.sdk.grounding.model;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/** RetrievalBinaryBooleanFilter */
// CHECKSTYLE:OFF
public class RetrievalBinaryBooleanFilter
// CHECKSTYLE:ON
{
  /** Gets or Sets operator */
  public enum OperatorEnum {
    /** The AND option of this RetrievalBinaryBooleanFilter */
    AND("and"),

    /** The OR option of this RetrievalBinaryBooleanFilter */
    OR("or"),

    /** The UNKNOWN_DEFAULT_OPEN_API option of this RetrievalBinaryBooleanFilter */
    UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");

    private String value;

    OperatorEnum(String value) {
      this.value = value;
    }

    /**
     * Get the value of the enum
     *
     * @return The enum value
     */
    @JsonValue
    @Nonnull
    public String getValue() {
      return value;
    }

    /**
     * Get the String value of the enum value.
     *
     * @return The enum value as String
     */
    @Override
    @Nonnull
    public String toString() {
      return String.valueOf(value);
    }

    /**
     * Get the enum value from a String value
     *
     * @param value The String value
     * @return The enum value of type RetrievalBinaryBooleanFilter
     */
    @JsonCreator
    @Nonnull
    public static OperatorEnum fromValue(@Nonnull final String value) {
      for (OperatorEnum b : OperatorEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return UNKNOWN_DEFAULT_OPEN_API;
    }
  }

  @JsonProperty("operator")
  private OperatorEnum operator;

  @JsonProperty("left")
  private Left left;

  @JsonProperty("right")
  private Right right;

  @JsonAnySetter @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

  /** Default constructor for RetrievalBinaryBooleanFilter. */
  protected RetrievalBinaryBooleanFilter() {}

  /**
   * Set the operator of this {@link RetrievalBinaryBooleanFilter} instance and return the same
   * instance.
   *
   * @param operator The operator of this {@link RetrievalBinaryBooleanFilter}
   * @return The same instance of this {@link RetrievalBinaryBooleanFilter} class
   */
  @Nonnull
  public RetrievalBinaryBooleanFilter operator(@Nonnull final OperatorEnum operator) {
    this.operator = operator;
    return this;
  }

  /**
   * Get operator
   *
   * @return operator The operator of this {@link RetrievalBinaryBooleanFilter} instance.
   */
  @Nonnull
  public OperatorEnum getOperator() {
    return operator;
  }

  /**
   * Set the operator of this {@link RetrievalBinaryBooleanFilter} instance.
   *
   * @param operator The operator of this {@link RetrievalBinaryBooleanFilter}
   */
  public void setOperator(@Nonnull final OperatorEnum operator) {
    this.operator = operator;
  }

  /**
   * Set the left of this {@link RetrievalBinaryBooleanFilter} instance and return the same
   * instance.
   *
   * @param left The left of this {@link RetrievalBinaryBooleanFilter}
   * @return The same instance of this {@link RetrievalBinaryBooleanFilter} class
   */
  @Nonnull
  public RetrievalBinaryBooleanFilter left(@Nonnull final Left left) {
    this.left = left;
    return this;
  }

  /**
   * Get left
   *
   * @return left The left of this {@link RetrievalBinaryBooleanFilter} instance.
   */
  @Nonnull
  public Left getLeft() {
    return left;
  }

  /**
   * Set the left of this {@link RetrievalBinaryBooleanFilter} instance.
   *
   * @param left The left of this {@link RetrievalBinaryBooleanFilter}
   */
  public void setLeft(@Nonnull final Left left) {
    this.left = left;
  }

  /**
   * Set the right of this {@link RetrievalBinaryBooleanFilter} instance and return the same
   * instance.
   *
   * @param right The right of this {@link RetrievalBinaryBooleanFilter}
   * @return The same instance of this {@link RetrievalBinaryBooleanFilter} class
   */
  @Nonnull
  public RetrievalBinaryBooleanFilter right(@Nonnull final Right right) {
    this.right = right;
    return this;
  }

  /**
   * Get right
   *
   * @return right The right of this {@link RetrievalBinaryBooleanFilter} instance.
   */
  @Nonnull
  public Right getRight() {
    return right;
  }

  /**
   * Set the right of this {@link RetrievalBinaryBooleanFilter} instance.
   *
   * @param right The right of this {@link RetrievalBinaryBooleanFilter}
   */
  public void setRight(@Nonnull final Right right) {
    this.right = right;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link RetrievalBinaryBooleanFilter}.
   *
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link RetrievalBinaryBooleanFilter}
   * instance.
   *
   * @deprecated Use {@link #toMap()} instead.
   * @param name The name of the property
   * @return The value of the property
   * @throws NoSuchElementException If no property with the given name could be found.
   */
  @Nullable
  @Deprecated
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if (!cloudSdkCustomFields.containsKey(name)) {
      throw new NoSuchElementException(
          "RetrievalBinaryBooleanFilter has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Get the value of all properties of this {@link RetrievalBinaryBooleanFilter} instance including
   * unrecognized properties.
   *
   * @return The map of all properties
   */
  @JsonIgnore
  @Nonnull
  public Map<String, Object> toMap() {
    final Map<String, Object> declaredFields = new LinkedHashMap<>(cloudSdkCustomFields);
    if (operator != null) declaredFields.put("operator", operator);
    if (left != null) declaredFields.put("left", left);
    if (right != null) declaredFields.put("right", right);
    return declaredFields;
  }

  /**
   * Set an unrecognizable property of this {@link RetrievalBinaryBooleanFilter} instance. If the
   * map previously contained a mapping for the key, the old value is replaced by the specified
   * value.
   *
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField(@Nonnull String customFieldName, @Nullable Object customFieldValue) {
    cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }

  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final RetrievalBinaryBooleanFilter retrievalBinaryBooleanFilter =
        (RetrievalBinaryBooleanFilter) o;
    return Objects.equals(
            this.cloudSdkCustomFields, retrievalBinaryBooleanFilter.cloudSdkCustomFields)
        && Objects.equals(this.operator, retrievalBinaryBooleanFilter.operator)
        && Objects.equals(this.left, retrievalBinaryBooleanFilter.left)
        && Objects.equals(this.right, retrievalBinaryBooleanFilter.right);
  }

  @Override
  public int hashCode() {
    return Objects.hash(operator, left, right, cloudSdkCustomFields);
  }

  @Override
  @Nonnull
  public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class RetrievalBinaryBooleanFilter {\n");
    sb.append("    operator: ").append(toIndentedString(operator)).append("\n");
    sb.append("    left: ").append(toIndentedString(left)).append("\n");
    sb.append("    right: ").append(toIndentedString(right)).append("\n");
    cloudSdkCustomFields.forEach(
        (k, v) ->
            sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Create a type-safe, fluent-api builder object to construct a new {@link
   * RetrievalBinaryBooleanFilter} instance with all required arguments.
   */
  public static Builder create() {
    return (operator) ->
        (left) ->
            (right) ->
                new RetrievalBinaryBooleanFilter().operator(operator).left(left).right(right);
  }

  /** Builder helper class. */
  public interface Builder {
    /**
     * Set the operator of this {@link RetrievalBinaryBooleanFilter} instance.
     *
     * @param operator The operator of this {@link RetrievalBinaryBooleanFilter}
     * @return The RetrievalBinaryBooleanFilter builder.
     */
    Builder1 operator(@Nonnull final OperatorEnum operator);
  }

  /** Builder helper class. */
  public interface Builder1 {
    /**
     * Set the left of this {@link RetrievalBinaryBooleanFilter} instance.
     *
     * @param left The left of this {@link RetrievalBinaryBooleanFilter}
     * @return The RetrievalBinaryBooleanFilter builder.
     */
    Builder2 left(@Nonnull final Left left);
  }

  /** Builder helper class. */
  public interface Builder2 {
    /**
     * Set the right of this {@link RetrievalBinaryBooleanFilter} instance.
     *
     * @param right The right of this {@link RetrievalBinaryBooleanFilter}
     * @return The RetrievalBinaryBooleanFilter instance.
     */
    RetrievalBinaryBooleanFilter right(@Nonnull final Right right);
  }
}
