/*
 * Grounding
 * Grounding is a service designed to handle data-related tasks, such as grounding and retrieval, using vector databases. It provides specialized data retrieval through these databases, grounding the retrieval process with your own external and context-relevant data. Grounding combines generative AI capabilities with the ability to use real-time, precise data to improve decision-making and business operations for specific AI-driven business solutions.
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.ai.sdk.grounding.model;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/** Search */
// CHECKSTYLE:OFF
public class Search
// CHECKSTYLE:ON
{
  @JsonProperty("dataRepositoryMetadata")
  private List<MetaDataKeyValuePairStrict> dataRepositoryMetadata = new ArrayList<>();

  @JsonAnySetter @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

  /** Default constructor for Search. */
  protected Search() {}

  /**
   * Set the dataRepositoryMetadata of this {@link Search} instance and return the same instance.
   *
   * @param dataRepositoryMetadata The dataRepositoryMetadata of this {@link Search}
   * @return The same instance of this {@link Search} class
   */
  @Nonnull
  public Search dataRepositoryMetadata(
      @Nonnull final List<MetaDataKeyValuePairStrict> dataRepositoryMetadata) {
    this.dataRepositoryMetadata = dataRepositoryMetadata;
    return this;
  }

  /**
   * Add one dataRepositoryMetadata instance to this {@link Search}.
   *
   * @param dataRepositoryMetadataItem The dataRepositoryMetadata that should be added
   * @return The same instance of type {@link Search}
   */
  @Nonnull
  public Search addDataRepositoryMetadataItem(
      @Nonnull final MetaDataKeyValuePairStrict dataRepositoryMetadataItem) {
    if (this.dataRepositoryMetadata == null) {
      this.dataRepositoryMetadata = new ArrayList<>();
    }
    this.dataRepositoryMetadata.add(dataRepositoryMetadataItem);
    return this;
  }

  /**
   * Get dataRepositoryMetadata
   *
   * @return dataRepositoryMetadata The dataRepositoryMetadata of this {@link Search} instance.
   */
  @Nonnull
  public List<MetaDataKeyValuePairStrict> getDataRepositoryMetadata() {
    return dataRepositoryMetadata;
  }

  /**
   * Set the dataRepositoryMetadata of this {@link Search} instance.
   *
   * @param dataRepositoryMetadata The dataRepositoryMetadata of this {@link Search}
   */
  public void setDataRepositoryMetadata(
      @Nonnull final List<MetaDataKeyValuePairStrict> dataRepositoryMetadata) {
    this.dataRepositoryMetadata = dataRepositoryMetadata;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link Search}.
   *
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link Search} instance.
   *
   * @deprecated Use {@link #toMap()} instead.
   * @param name The name of the property
   * @return The value of the property
   * @throws NoSuchElementException If no property with the given name could be found.
   */
  @Nullable
  @Deprecated
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if (!cloudSdkCustomFields.containsKey(name)) {
      throw new NoSuchElementException("Search has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Get the value of all properties of this {@link Search} instance including unrecognized
   * properties.
   *
   * @return The map of all properties
   */
  @JsonIgnore
  @Nonnull
  public Map<String, Object> toMap() {
    final Map<String, Object> declaredFields = new LinkedHashMap<>(cloudSdkCustomFields);
    if (dataRepositoryMetadata != null)
      declaredFields.put("dataRepositoryMetadata", dataRepositoryMetadata);
    return declaredFields;
  }

  /**
   * Set an unrecognizable property of this {@link Search} instance. If the map previously contained
   * a mapping for the key, the old value is replaced by the specified value.
   *
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField(@Nonnull String customFieldName, @Nullable Object customFieldValue) {
    cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }

  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final Search search = (Search) o;
    return Objects.equals(this.cloudSdkCustomFields, search.cloudSdkCustomFields)
        && Objects.equals(this.dataRepositoryMetadata, search.dataRepositoryMetadata);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dataRepositoryMetadata, cloudSdkCustomFields);
  }

  @Override
  @Nonnull
  public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class Search {\n");
    sb.append("    dataRepositoryMetadata: ")
        .append(toIndentedString(dataRepositoryMetadata))
        .append("\n");
    cloudSdkCustomFields.forEach(
        (k, v) ->
            sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Create a type-safe, fluent-api builder object to construct a new {@link Search} instance with
   * all required arguments.
   */
  public static Builder create() {
    return (dataRepositoryMetadata) -> new Search().dataRepositoryMetadata(dataRepositoryMetadata);
  }

  /** Builder helper class. */
  public interface Builder {
    /**
     * Set the dataRepositoryMetadata of this {@link Search} instance.
     *
     * @param dataRepositoryMetadata The dataRepositoryMetadata of this {@link Search}
     * @return The Search instance.
     */
    Search dataRepositoryMetadata(
        @Nonnull final List<MetaDataKeyValuePairStrict> dataRepositoryMetadata);

    /**
     * Set the dataRepositoryMetadata of this {@link Search} instance.
     *
     * @param dataRepositoryMetadata The dataRepositoryMetadata of this {@link Search}
     * @return The Search instance.
     */
    default Search dataRepositoryMetadata(
        @Nonnull final MetaDataKeyValuePairStrict... dataRepositoryMetadata) {
      return dataRepositoryMetadata(Arrays.asList(dataRepositoryMetadata));
    }
  }
}
