

/*
 * Internal Orchestration Service API
 * SAP AI Core - Orchestration Service API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.ai.sdk.orchestration.client.model;

import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.sap.ai.sdk.orchestration.client.model.Masking;
import com.sap.ai.sdk.orchestration.client.model.UnmaskingConfig;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * MaskingModuleConfig
 */
// CHECKSTYLE:OFF
public class MaskingModuleConfig 
// CHECKSTYLE:ON
{
  @JsonProperty("masking")
  private List<Masking> masking = new ArrayList<>();

  @JsonProperty("unmasking")
  private UnmaskingConfig unmasking;

  @JsonAnySetter
  @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

   /**
    * Set the masking of this {@link MaskingModuleConfig} instance and return the same instance.
    *
    * @param masking  Masking services to be used
    * @return The same instance of this {@link MaskingModuleConfig} class
    */
   @Nonnull public MaskingModuleConfig masking(@Nonnull final List<Masking> masking) {
    this.masking = masking;
    return this;
  }
  /**
   * Add one masking instance to this {@link MaskingModuleConfig}.
   * @param maskingItem The masking that should be added
   * @return The same instance of type {@link MaskingModuleConfig}
   */
  @Nonnull public MaskingModuleConfig addMaskingItem( @Nonnull final Masking maskingItem) {
    if (this.masking == null) {
      this.masking = new ArrayList<>();
    }
    this.masking.add(maskingItem);
    return this;
  }

   /**
    * Masking services to be used
    * @return masking  The masking of this {@link MaskingModuleConfig} instance.
    */
  @Nonnull public List<Masking> getMasking() {
    return masking;
  }

  /**
   * Set the masking of this {@link MaskingModuleConfig} instance.
   *
   * @param masking  Masking services to be used
   */
  public void setMasking( @Nonnull final List<Masking> masking) {
    this.masking = masking;
  }

   /**
    * Set the unmasking of this {@link MaskingModuleConfig} instance and return the same instance.
    *
    * @param unmasking  The unmasking of this {@link MaskingModuleConfig}
    * @return The same instance of this {@link MaskingModuleConfig} class
    */
   @Nonnull public MaskingModuleConfig unmasking(@Nonnull final UnmaskingConfig unmasking) {
    this.unmasking = unmasking;
    return this;
  }

   /**
    * Get unmasking
    * @return unmasking  The unmasking of this {@link MaskingModuleConfig} instance.
    */
  @Nonnull public UnmaskingConfig getUnmasking() {
    return unmasking;
  }

  /**
   * Set the unmasking of this {@link MaskingModuleConfig} instance.
   *
   * @param unmasking  The unmasking of this {@link MaskingModuleConfig}
   */
  public void setUnmasking( @Nonnull final UnmaskingConfig unmasking) {
    this.unmasking = unmasking;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link MaskingModuleConfig}.
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link MaskingModuleConfig} instance.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("MaskingModuleConfig has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Set an unrecognizable property of this {@link MaskingModuleConfig} instance. If the map previously contained a mapping
   * for the key, the old value is replaced by the specified value.
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField( @Nonnull String customFieldName, @Nullable Object customFieldValue )
  {
      cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }


  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final MaskingModuleConfig maskingModuleConfig = (MaskingModuleConfig) o;
    return Objects.equals(this.cloudSdkCustomFields, maskingModuleConfig.cloudSdkCustomFields) &&
        Objects.equals(this.masking, maskingModuleConfig.masking) &&
        Objects.equals(this.unmasking, maskingModuleConfig.unmasking);
  }

  @Override
  public int hashCode() {
    return Objects.hash(masking, unmasking, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class MaskingModuleConfig {\n");
    sb.append("    masking: ").append(toIndentedString(masking)).append("\n");
    sb.append("    unmasking: ").append(toIndentedString(unmasking)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


}

