

/*
 * AI Core
 * Provides tools to manage your scenarios and workflows in SAP AI Core. Execute pipelines as a batch job, for example to pre-process or train your models, or perform batch inference.  Serve inference requests of trained models. Deploy а trained machine learning model as a web service to serve inference requests with high performance.  Register your own Docker registry, synchronize your AI content from your own git repository, and register your own object store for training data and trained models. 
 *
 * The version of the OpenAPI document: 2.32.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.ai.sdk.core.client.model;

import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.sap.ai.sdk.core.client.model.BckndNestedUsageItem;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * BckndUsageResourcePlanItem
 */

// CHECKSTYLE:OFF
public class BckndUsageResourcePlanItem 
// CHECKSTYLE:ON
{
  @JsonProperty("plan")
  private String plan;

  @JsonProperty("count")
  private Integer count;

  @JsonProperty("usage")
  private List<BckndNestedUsageItem> usage = new ArrayList<>();

  @JsonAnySetter
  @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

   /**
   * Set the plan of this {@link BckndUsageResourcePlanItem} instance and return the same instance.
   *
   * @param plan  The plan of this {@link BckndUsageResourcePlanItem}
   * @return The same instance of this {@link BckndUsageResourcePlanItem} class
   */
   @Nonnull public BckndUsageResourcePlanItem plan(@Nonnull final String plan) {
    this.plan = plan;
    return this;
  }

   /**
   * Get plan
   * @return plan  The plan of this {@link BckndUsageResourcePlanItem} instance.
  **/
  @Nonnull public String getPlan() {
    return plan;
  }

  /**
  * Set the plan of this {@link BckndUsageResourcePlanItem} instance.
  *
  * @param plan  The plan of this {@link BckndUsageResourcePlanItem}
  */
  public void setPlan( @Nonnull final String plan) {
    this.plan = plan;
  }

   /**
   * Set the count of this {@link BckndUsageResourcePlanItem} instance and return the same instance.
   *
   * @param count  The count of this {@link BckndUsageResourcePlanItem}
   * @return The same instance of this {@link BckndUsageResourcePlanItem} class
   */
   @Nonnull public BckndUsageResourcePlanItem count(@Nonnull final Integer count) {
    this.count = count;
    return this;
  }

   /**
   * Get count
   * @return count  The count of this {@link BckndUsageResourcePlanItem} instance.
  **/
  @Nonnull public Integer getCount() {
    return count;
  }

  /**
  * Set the count of this {@link BckndUsageResourcePlanItem} instance.
  *
  * @param count  The count of this {@link BckndUsageResourcePlanItem}
  */
  public void setCount( @Nonnull final Integer count) {
    this.count = count;
  }

   /**
   * Set the usage of this {@link BckndUsageResourcePlanItem} instance and return the same instance.
   *
   * @param usage  The usage of this {@link BckndUsageResourcePlanItem}
   * @return The same instance of this {@link BckndUsageResourcePlanItem} class
   */
   @Nonnull public BckndUsageResourcePlanItem usage(@Nonnull final List<BckndNestedUsageItem> usage) {
    this.usage = usage;
    return this;
  }
  /**
  * Add one usage instance to this {@link BckndUsageResourcePlanItem}.
  * @param usageItem The usage that should be added
  * @return The same instance of type {@link BckndUsageResourcePlanItem}
  */
  @Nonnull public BckndUsageResourcePlanItem addusageItem( @Nonnull final BckndNestedUsageItem usageItem) {
    if (this.usage == null) {
      this.usage = new ArrayList<>();
    }
    this.usage.add(usageItem);
    return this;
  }

   /**
   * Get usage
   * @return usage  The usage of this {@link BckndUsageResourcePlanItem} instance.
  **/
  @Nonnull public List<BckndNestedUsageItem> getUsage() {
    return usage;
  }

  /**
  * Set the usage of this {@link BckndUsageResourcePlanItem} instance.
  *
  * @param usage  The usage of this {@link BckndUsageResourcePlanItem}
  */
  public void setUsage( @Nonnull final List<BckndNestedUsageItem> usage) {
    this.usage = usage;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link BckndUsageResourcePlanItem}.
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link BckndUsageResourcePlanItem} instance.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("BckndUsageResourcePlanItem has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Set an unrecognizable property of this {@link BckndUsageResourcePlanItem} instance. If the map previously contained a mapping
   * for the key, the old value is replaced by the specified value.
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField( @Nonnull String customFieldName, @Nullable Object customFieldValue )
  {
      cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }


  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final BckndUsageResourcePlanItem bckndUsageResourcePlanItem = (BckndUsageResourcePlanItem) o;
    return Objects.equals(this.cloudSdkCustomFields, bckndUsageResourcePlanItem.cloudSdkCustomFields) &&
        Objects.equals(this.plan, bckndUsageResourcePlanItem.plan) &&
        Objects.equals(this.count, bckndUsageResourcePlanItem.count) &&
        Objects.equals(this.usage, bckndUsageResourcePlanItem.usage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(plan, count, usage, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class BckndUsageResourcePlanItem {\n");
    sb.append("    plan: ").append(toIndentedString(plan)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    usage: ").append(toIndentedString(usage)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

