/*
 * Internal Orchestration Service API
 * Orchestration is an inference service which provides common additional capabilities for business AI scenarios, such as content filtering and data masking. At the core of the service is the LLM module which allows for an easy, harmonized access to the language models of gen AI hub. The service is designed to be modular and extensible, allowing for the addition of new modules in the future. Each module can be configured independently and at runtime, allowing for a high degree of flexibility in the orchestration of AI services.
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.ai.sdk.orchestration.model;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/** InputTranslationModuleResultData */
// CHECKSTYLE:OFF
public class InputTranslationModuleResultData
// CHECKSTYLE:ON
{
  @JsonProperty("translated_template")
  private String translatedTemplate;

  @JsonProperty("translated_template_roles")
  private Map<String, List<String>> translatedTemplateRoles = new HashMap<>();

  @JsonProperty("translated_placeholders")
  private Map<String, String> translatedPlaceholders = new HashMap<>();

  @JsonAnySetter @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

  /** Default constructor for InputTranslationModuleResultData. */
  protected InputTranslationModuleResultData() {}

  /**
   * Set the translatedTemplate of this {@link InputTranslationModuleResultData} instance and return
   * the same instance.
   *
   * @param translatedTemplate The translatedTemplate of this {@link
   *     InputTranslationModuleResultData}
   * @return The same instance of this {@link InputTranslationModuleResultData} class
   */
  @Nonnull
  public InputTranslationModuleResultData translatedTemplate(
      @Nullable final String translatedTemplate) {
    this.translatedTemplate = translatedTemplate;
    return this;
  }

  /**
   * Get translatedTemplate
   *
   * @return translatedTemplate The translatedTemplate of this {@link
   *     InputTranslationModuleResultData} instance.
   * @deprecated
   */
  @Deprecated
  @Nonnull
  public String getTranslatedTemplate() {
    return translatedTemplate;
  }

  /**
   * Set the translatedTemplate of this {@link InputTranslationModuleResultData} instance.
   *
   * @param translatedTemplate The translatedTemplate of this {@link
   *     InputTranslationModuleResultData}
   */
  public void setTranslatedTemplate(@Nullable final String translatedTemplate) {
    this.translatedTemplate = translatedTemplate;
  }

  /**
   * Set the translatedTemplateRoles of this {@link InputTranslationModuleResultData} instance and
   * return the same instance.
   *
   * @param translatedTemplateRoles The translatedTemplateRoles of this {@link
   *     InputTranslationModuleResultData}
   * @return The same instance of this {@link InputTranslationModuleResultData} class
   */
  @Nonnull
  public InputTranslationModuleResultData translatedTemplateRoles(
      @Nullable final Map<String, List<String>> translatedTemplateRoles) {
    this.translatedTemplateRoles = translatedTemplateRoles;
    return this;
  }

  /**
   * Put one translatedTemplateRoles instance to this {@link InputTranslationModuleResultData}
   * instance.
   *
   * @param key The String key of this translatedTemplateRoles instance
   * @param translatedTemplateRolesItem The translatedTemplateRoles that should be added under the
   *     given key
   * @return The same instance of type {@link InputTranslationModuleResultData}
   */
  @Nonnull
  public InputTranslationModuleResultData puttranslatedTemplateRolesItem(
      @Nonnull final String key, @Nonnull final List<String> translatedTemplateRolesItem) {
    if (this.translatedTemplateRoles == null) {
      this.translatedTemplateRoles = new HashMap<>();
    }
    this.translatedTemplateRoles.put(key, translatedTemplateRolesItem);
    return this;
  }

  /**
   * Get translatedTemplateRoles
   *
   * @return translatedTemplateRoles The translatedTemplateRoles of this {@link
   *     InputTranslationModuleResultData} instance.
   */
  @Nonnull
  public Map<String, List<String>> getTranslatedTemplateRoles() {
    return translatedTemplateRoles;
  }

  /**
   * Set the translatedTemplateRoles of this {@link InputTranslationModuleResultData} instance.
   *
   * @param translatedTemplateRoles The translatedTemplateRoles of this {@link
   *     InputTranslationModuleResultData}
   */
  public void setTranslatedTemplateRoles(
      @Nullable final Map<String, List<String>> translatedTemplateRoles) {
    this.translatedTemplateRoles = translatedTemplateRoles;
  }

  /**
   * Set the translatedPlaceholders of this {@link InputTranslationModuleResultData} instance and
   * return the same instance.
   *
   * @param translatedPlaceholders The translatedPlaceholders of this {@link
   *     InputTranslationModuleResultData}
   * @return The same instance of this {@link InputTranslationModuleResultData} class
   */
  @Nonnull
  public InputTranslationModuleResultData translatedPlaceholders(
      @Nullable final Map<String, String> translatedPlaceholders) {
    this.translatedPlaceholders = translatedPlaceholders;
    return this;
  }

  /**
   * Put one translatedPlaceholders instance to this {@link InputTranslationModuleResultData}
   * instance.
   *
   * @param key The String key of this translatedPlaceholders instance
   * @param translatedPlaceholdersItem The translatedPlaceholders that should be added under the
   *     given key
   * @return The same instance of type {@link InputTranslationModuleResultData}
   */
  @Nonnull
  public InputTranslationModuleResultData puttranslatedPlaceholdersItem(
      @Nonnull final String key, @Nonnull final String translatedPlaceholdersItem) {
    if (this.translatedPlaceholders == null) {
      this.translatedPlaceholders = new HashMap<>();
    }
    this.translatedPlaceholders.put(key, translatedPlaceholdersItem);
    return this;
  }

  /**
   * Get translatedPlaceholders
   *
   * @return translatedPlaceholders The translatedPlaceholders of this {@link
   *     InputTranslationModuleResultData} instance.
   */
  @Nonnull
  public Map<String, String> getTranslatedPlaceholders() {
    return translatedPlaceholders;
  }

  /**
   * Set the translatedPlaceholders of this {@link InputTranslationModuleResultData} instance.
   *
   * @param translatedPlaceholders The translatedPlaceholders of this {@link
   *     InputTranslationModuleResultData}
   */
  public void setTranslatedPlaceholders(
      @Nullable final Map<String, String> translatedPlaceholders) {
    this.translatedPlaceholders = translatedPlaceholders;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link InputTranslationModuleResultData}.
   *
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link InputTranslationModuleResultData}
   * instance.
   *
   * @deprecated Use {@link #toMap()} instead.
   * @param name The name of the property
   * @return The value of the property
   * @throws NoSuchElementException If no property with the given name could be found.
   */
  @Nullable
  @Deprecated
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if (!cloudSdkCustomFields.containsKey(name)) {
      throw new NoSuchElementException(
          "InputTranslationModuleResultData has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Get the value of all properties of this {@link InputTranslationModuleResultData} instance
   * including unrecognized properties.
   *
   * @return The map of all properties
   */
  @JsonIgnore
  @Nonnull
  public Map<String, Object> toMap() {
    final Map<String, Object> declaredFields = new LinkedHashMap<>(cloudSdkCustomFields);
    if (translatedTemplate != null) declaredFields.put("translatedTemplate", translatedTemplate);
    if (translatedTemplateRoles != null)
      declaredFields.put("translatedTemplateRoles", translatedTemplateRoles);
    if (translatedPlaceholders != null)
      declaredFields.put("translatedPlaceholders", translatedPlaceholders);
    return declaredFields;
  }

  /**
   * Set an unrecognizable property of this {@link InputTranslationModuleResultData} instance. If
   * the map previously contained a mapping for the key, the old value is replaced by the specified
   * value.
   *
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField(@Nonnull String customFieldName, @Nullable Object customFieldValue) {
    cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }

  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final InputTranslationModuleResultData inputTranslationModuleResultData =
        (InputTranslationModuleResultData) o;
    return Objects.equals(
            this.cloudSdkCustomFields, inputTranslationModuleResultData.cloudSdkCustomFields)
        && Objects.equals(
            this.translatedTemplate, inputTranslationModuleResultData.translatedTemplate)
        && Objects.equals(
            this.translatedTemplateRoles, inputTranslationModuleResultData.translatedTemplateRoles)
        && Objects.equals(
            this.translatedPlaceholders, inputTranslationModuleResultData.translatedPlaceholders);
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        translatedTemplate, translatedTemplateRoles, translatedPlaceholders, cloudSdkCustomFields);
  }

  @Override
  @Nonnull
  public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class InputTranslationModuleResultData {\n");
    sb.append("    translatedTemplate: ").append(toIndentedString(translatedTemplate)).append("\n");
    sb.append("    translatedTemplateRoles: ")
        .append(toIndentedString(translatedTemplateRoles))
        .append("\n");
    sb.append("    translatedPlaceholders: ")
        .append(toIndentedString(translatedPlaceholders))
        .append("\n");
    cloudSdkCustomFields.forEach(
        (k, v) ->
            sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /** Create a new {@link InputTranslationModuleResultData} instance. No arguments are required. */
  public static InputTranslationModuleResultData create() {
    return new InputTranslationModuleResultData();
  }
}
