

/*
 * Orchestration v2
 * Orchestration is an inference service which provides common additional capabilities for business AI scenarios, such as content filtering and data masking. At the core of the service is the LLM module which allows for an easy, harmonized access to the language models of gen AI hub. The service is designed to be modular and extensible, allowing for the addition of new modules in the future. Each module can be configured independently and at runtime, allowing for a high degree of flexibility in the orchestration of AI services.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.ai.sdk.orchestration.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.sap.ai.sdk.orchestration.model.SAPDocumentTranslationApplyToSelector;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * SAPDocumentTranslationOutputTargetLanguage
 */
public interface SAPDocumentTranslationOutputTargetLanguage  {
    /**
     * Helper class to create {@code String } that implements {@link SAPDocumentTranslationOutputTargetLanguage}.
     */
    record InnerString(@com.fasterxml.jackson.annotation.JsonValue @Nonnull String value) implements SAPDocumentTranslationOutputTargetLanguage {}

    /**
     * Creator to enable deserialization of {@code String }.
     *
     * @param val the value to use
     * @return a new instance of {@link InnerString}.
     */
    @com.fasterxml.jackson.annotation.JsonCreator
    @Nonnull
    static InnerString create( @Nonnull final String val) { return new InnerString(val); }

    /**
     * Helper class to create {@code SAPDocumentTranslationApplyToSelector } that implements {@link SAPDocumentTranslationOutputTargetLanguage}.
     */
    record InnerSAPDocumentTranslationApplyToSelector(@com.fasterxml.jackson.annotation.JsonValue @Nonnull SAPDocumentTranslationApplyToSelector value) implements SAPDocumentTranslationOutputTargetLanguage {}

    /**
     * Creator to enable deserialization of {@code SAPDocumentTranslationApplyToSelector }.
     *
     * @param val the value to use
     * @return a new instance of {@link InnerSAPDocumentTranslationApplyToSelector}.
     */
    @com.fasterxml.jackson.annotation.JsonCreator
    @Nonnull
    static InnerSAPDocumentTranslationApplyToSelector createInnerSAPDocumentTranslationApplyToSelector( @Nonnull final SAPDocumentTranslationApplyToSelector val) { return new InnerSAPDocumentTranslationApplyToSelector(val); }

}

