

/*
 * Orchestration v2
 * Orchestration is an inference service which provides common additional capabilities for business AI scenarios, such as content filtering and data masking. At the core of the service is the LLM module which allows for an easy, harmonized access to the language models of gen AI hub. The service is designed to be modular and extensible, allowing for the addition of new modules in the future. Each module can be configured independently and at runtime, allowing for a high degree of flexibility in the orchestration of AI services.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.ai.sdk.orchestration.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.sap.ai.sdk.orchestration.model.TemplateRefTemplateRef;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * TemplateRef
 */
// CHECKSTYLE:OFF
public class TemplateRef implements PromptTemplatingModuleConfigPrompt 
// CHECKSTYLE:ON
{
  @JsonProperty("template_ref")
  private TemplateRefTemplateRef templateRef;

  @JsonAnySetter
  @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();
  /**
   * Default constructor for TemplateRef.
   */
  protected TemplateRef() {  }

  /**
   * Set the templateRef of this {@link TemplateRef} instance and return the same instance.
   *
   * @param templateRef  The templateRef of this {@link TemplateRef}
   * @return The same instance of this {@link TemplateRef} class
   */
  @Nonnull public TemplateRef templateRef( @Nonnull final TemplateRefTemplateRef templateRef) {
    this.templateRef = templateRef;
    return this;
  }

  /**
   * Get templateRef
   * @return templateRef  The templateRef of this {@link TemplateRef} instance.
   */
  @Nonnull
  public TemplateRefTemplateRef getTemplateRef() {
    return templateRef;
  }

  /**
   * Set the templateRef of this {@link TemplateRef} instance.
   *
   * @param templateRef  The templateRef of this {@link TemplateRef}
   */
  public void setTemplateRef( @Nonnull final TemplateRefTemplateRef templateRef) {
    this.templateRef = templateRef;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link TemplateRef}.
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link TemplateRef} instance.
   * @deprecated Use {@link #toMap()} instead.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  @Deprecated
  public Object getCustomField( @Nonnull final String name ) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("TemplateRef has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Get the value of all properties of this {@link TemplateRef} instance including unrecognized properties.
   *
   * @return The map of all properties
   */
  @JsonIgnore
  @Nonnull
  public Map<String, Object> toMap()
  {
    final Map<String, Object> declaredFields = new LinkedHashMap<>(cloudSdkCustomFields);
    if( templateRef != null ) declaredFields.put("templateRef", templateRef);
    return declaredFields;
  }

  /**
   * Set an unrecognizable property of this {@link TemplateRef} instance. If the map previously contained a mapping
   * for the key, the old value is replaced by the specified value.
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField( @Nonnull String customFieldName, @Nullable Object customFieldValue )
  {
      cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }


  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final TemplateRef templateRef = (TemplateRef) o;
    return Objects.equals(this.cloudSdkCustomFields, templateRef.cloudSdkCustomFields) &&
        Objects.equals(this.templateRef, templateRef.templateRef);
  }

  @Override
  public int hashCode() {
    return Objects.hash(templateRef, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class TemplateRef {\n");
    sb.append("    templateRef: ").append(toIndentedString(templateRef)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
    /**
    * Create a type-safe, fluent-api builder object to construct a new {@link TemplateRef} instance with all required arguments.
    */
    public static Builder create() {
        return (templateRef) -> new TemplateRef().templateRef(templateRef);
    }
    /**
    * Builder helper class.
    */
    public interface Builder {
        /**
        * Set the templateRef of this {@link TemplateRef} instance.
        *
        * @param templateRef  The templateRef of this {@link TemplateRef}
        * @return The TemplateRef instance.
        */
        TemplateRef templateRef( @Nonnull final TemplateRefTemplateRef templateRef);
    }

}

