

/*
 * Orchestration v2
 * Orchestration is an inference service which provides common additional capabilities for business AI scenarios, such as content filtering and data masking. At the core of the service is the LLM module which allows for an easy, harmonized access to the language models of gen AI hub. The service is designed to be modular and extensible, allowing for the addition of new modules in the future. Each module can be configured independently and at runtime, allowing for a high degree of flexibility in the orchestration of AI services.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.ai.sdk.orchestration.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * Breakdown of tokens used in a completion.
 */
// CHECKSTYLE:OFF
public class TokenUsageCompletionTokensDetails 
// CHECKSTYLE:ON
{
  @JsonProperty("accepted_prediction_tokens")
  private Integer acceptedPredictionTokens;

  @JsonProperty("audio_tokens")
  private Integer audioTokens;

  @JsonProperty("reasoning_tokens")
  private Integer reasoningTokens;

  @JsonProperty("rejected_prediction_tokens")
  private Integer rejectedPredictionTokens;

  @JsonAnySetter
  @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();
  /**
   * Default constructor for TokenUsageCompletionTokensDetails.
   */
  protected TokenUsageCompletionTokensDetails() {  }

  /**
   * Set the acceptedPredictionTokens of this {@link TokenUsageCompletionTokensDetails} instance and return the same instance.
   *
   * @param acceptedPredictionTokens  When using Predicted Outputs, the number of tokens in the prediction that appeared in the completion. 
   * @return The same instance of this {@link TokenUsageCompletionTokensDetails} class
   */
  @Nonnull public TokenUsageCompletionTokensDetails acceptedPredictionTokens( @Nullable final Integer acceptedPredictionTokens) {
    this.acceptedPredictionTokens = acceptedPredictionTokens;
    return this;
  }

  /**
   * When using Predicted Outputs, the number of tokens in the prediction that appeared in the completion. 
   * @return acceptedPredictionTokens  The acceptedPredictionTokens of this {@link TokenUsageCompletionTokensDetails} instance.
   */
  @Nonnull
  public Integer getAcceptedPredictionTokens() {
    return acceptedPredictionTokens;
  }

  /**
   * Set the acceptedPredictionTokens of this {@link TokenUsageCompletionTokensDetails} instance.
   *
   * @param acceptedPredictionTokens  When using Predicted Outputs, the number of tokens in the prediction that appeared in the completion. 
   */
  public void setAcceptedPredictionTokens( @Nullable final Integer acceptedPredictionTokens) {
    this.acceptedPredictionTokens = acceptedPredictionTokens;
  }

  /**
   * Set the audioTokens of this {@link TokenUsageCompletionTokensDetails} instance and return the same instance.
   *
   * @param audioTokens  Audio input tokens generated by the model.
   * @return The same instance of this {@link TokenUsageCompletionTokensDetails} class
   */
  @Nonnull public TokenUsageCompletionTokensDetails audioTokens( @Nullable final Integer audioTokens) {
    this.audioTokens = audioTokens;
    return this;
  }

  /**
   * Audio input tokens generated by the model.
   * @return audioTokens  The audioTokens of this {@link TokenUsageCompletionTokensDetails} instance.
   */
  @Nonnull
  public Integer getAudioTokens() {
    return audioTokens;
  }

  /**
   * Set the audioTokens of this {@link TokenUsageCompletionTokensDetails} instance.
   *
   * @param audioTokens  Audio input tokens generated by the model.
   */
  public void setAudioTokens( @Nullable final Integer audioTokens) {
    this.audioTokens = audioTokens;
  }

  /**
   * Set the reasoningTokens of this {@link TokenUsageCompletionTokensDetails} instance and return the same instance.
   *
   * @param reasoningTokens  Tokens generated by the model for reasoning.
   * @return The same instance of this {@link TokenUsageCompletionTokensDetails} class
   */
  @Nonnull public TokenUsageCompletionTokensDetails reasoningTokens( @Nullable final Integer reasoningTokens) {
    this.reasoningTokens = reasoningTokens;
    return this;
  }

  /**
   * Tokens generated by the model for reasoning.
   * @return reasoningTokens  The reasoningTokens of this {@link TokenUsageCompletionTokensDetails} instance.
   */
  @Nonnull
  public Integer getReasoningTokens() {
    return reasoningTokens;
  }

  /**
   * Set the reasoningTokens of this {@link TokenUsageCompletionTokensDetails} instance.
   *
   * @param reasoningTokens  Tokens generated by the model for reasoning.
   */
  public void setReasoningTokens( @Nullable final Integer reasoningTokens) {
    this.reasoningTokens = reasoningTokens;
  }

  /**
   * Set the rejectedPredictionTokens of this {@link TokenUsageCompletionTokensDetails} instance and return the same instance.
   *
   * @param rejectedPredictionTokens  When using Predicted Outputs, the number of tokens in the prediction that did not appear in the completion. However, like reasoning tokens, these tokens are still counted in the total completion tokens for purposes of billing, output, and context window limits. 
   * @return The same instance of this {@link TokenUsageCompletionTokensDetails} class
   */
  @Nonnull public TokenUsageCompletionTokensDetails rejectedPredictionTokens( @Nullable final Integer rejectedPredictionTokens) {
    this.rejectedPredictionTokens = rejectedPredictionTokens;
    return this;
  }

  /**
   * When using Predicted Outputs, the number of tokens in the prediction that did not appear in the completion. However, like reasoning tokens, these tokens are still counted in the total completion tokens for purposes of billing, output, and context window limits. 
   * @return rejectedPredictionTokens  The rejectedPredictionTokens of this {@link TokenUsageCompletionTokensDetails} instance.
   */
  @Nonnull
  public Integer getRejectedPredictionTokens() {
    return rejectedPredictionTokens;
  }

  /**
   * Set the rejectedPredictionTokens of this {@link TokenUsageCompletionTokensDetails} instance.
   *
   * @param rejectedPredictionTokens  When using Predicted Outputs, the number of tokens in the prediction that did not appear in the completion. However, like reasoning tokens, these tokens are still counted in the total completion tokens for purposes of billing, output, and context window limits. 
   */
  public void setRejectedPredictionTokens( @Nullable final Integer rejectedPredictionTokens) {
    this.rejectedPredictionTokens = rejectedPredictionTokens;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link TokenUsageCompletionTokensDetails}.
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link TokenUsageCompletionTokensDetails} instance.
   * @deprecated Use {@link #toMap()} instead.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  @Deprecated
  public Object getCustomField( @Nonnull final String name ) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("TokenUsageCompletionTokensDetails has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Get the value of all properties of this {@link TokenUsageCompletionTokensDetails} instance including unrecognized properties.
   *
   * @return The map of all properties
   */
  @JsonIgnore
  @Nonnull
  public Map<String, Object> toMap()
  {
    final Map<String, Object> declaredFields = new LinkedHashMap<>(cloudSdkCustomFields);
    if( acceptedPredictionTokens != null ) declaredFields.put("acceptedPredictionTokens", acceptedPredictionTokens);
    if( audioTokens != null ) declaredFields.put("audioTokens", audioTokens);
    if( reasoningTokens != null ) declaredFields.put("reasoningTokens", reasoningTokens);
    if( rejectedPredictionTokens != null ) declaredFields.put("rejectedPredictionTokens", rejectedPredictionTokens);
    return declaredFields;
  }

  /**
   * Set an unrecognizable property of this {@link TokenUsageCompletionTokensDetails} instance. If the map previously contained a mapping
   * for the key, the old value is replaced by the specified value.
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField( @Nonnull String customFieldName, @Nullable Object customFieldValue )
  {
      cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }


  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final TokenUsageCompletionTokensDetails tokenUsageCompletionTokensDetails = (TokenUsageCompletionTokensDetails) o;
    return Objects.equals(this.cloudSdkCustomFields, tokenUsageCompletionTokensDetails.cloudSdkCustomFields) &&
        Objects.equals(this.acceptedPredictionTokens, tokenUsageCompletionTokensDetails.acceptedPredictionTokens) &&
        Objects.equals(this.audioTokens, tokenUsageCompletionTokensDetails.audioTokens) &&
        Objects.equals(this.reasoningTokens, tokenUsageCompletionTokensDetails.reasoningTokens) &&
        Objects.equals(this.rejectedPredictionTokens, tokenUsageCompletionTokensDetails.rejectedPredictionTokens);
  }

  @Override
  public int hashCode() {
    return Objects.hash(acceptedPredictionTokens, audioTokens, reasoningTokens, rejectedPredictionTokens, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class TokenUsageCompletionTokensDetails {\n");
    sb.append("    acceptedPredictionTokens: ").append(toIndentedString(acceptedPredictionTokens)).append("\n");
    sb.append("    audioTokens: ").append(toIndentedString(audioTokens)).append("\n");
    sb.append("    reasoningTokens: ").append(toIndentedString(reasoningTokens)).append("\n");
    sb.append("    rejectedPredictionTokens: ").append(toIndentedString(rejectedPredictionTokens)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
    /**
    * Create a new {@link TokenUsageCompletionTokensDetails} instance. No arguments are required.
    */
    public static TokenUsageCompletionTokensDetails create() {
        return new TokenUsageCompletionTokensDetails();
    }

}

