name: 'Cache Maven Dependencies'
permissions:
  contents: read
  actions: write

on:
  workflow_dispatch:
  schedule:
    - cron: '57 4 * * Sun'

env:
  MAVEN_CACHE_REF: refs/heads/main
  MAVEN_CACHE_KEY: maven-dependencies-sf1-test
  MAVEN_CACHE_DIR: ~/.m2

jobs:
  update-cache:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v7
        with:
          ref: ${{ env.MAVEN_CACHE_REF }}

      - name: 'Setup Java'
        uses: actions/setup-java@v5
        with:
          distribution: 'sapmachine'
          java-version: 21

      - name: 'Configure Artifactory Mirror'
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml << EOF
          <settings>
            <mirrors>
              <mirror>
                <id>artifactory-snapshots</id>
                <mirrorOf>central</mirrorOf>
                <url>https://common.repositories.cloud.sap/artifactory/maven-central</url>
              </mirror>
            </mirrors>
            <servers>
              <server>
                <id>artifactory-snapshots</id>
                <username>${ARTIFACTORY_USER}</username>
                <password>${ARTIFACTORY_PASS}</password>
              </server>
            </servers>
          </settings>
          EOF
        env:
          ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_COMMON_USER }}
          ARTIFACTORY_PASS: ${{ secrets.ARTIFACTORY_COMMON_PASSWORD }}

      - name: 'Download Dependencies'
        run: mvn -B dependency:go-offline

      - name: 'Delete Existing Caches'
        run: |
          CACHE_IDS=$(gh cache list --key "${{ env.MAVEN_CACHE_KEY }}" --ref "${{ env.MAVEN_CACHE_REF }}" --json id | jq -r '.[] | .id')
          for CACHE_ID in $CACHE_IDS; do
              echo "Deleting cache with ID: $CACHE_ID"
              gh cache delete "${CACHE_ID}"
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Cache Dependencies'
        uses: actions/cache/save@v6
        with:
          path: ${{ env.MAVEN_CACHE_DIR }}
          key: ${{ env.MAVEN_CACHE_KEY }}
