name: Update Vulnerability Database

on:
  workflow_dispatch:
  schedule:
    - cron: '46 20 * * 2' # use a somewhat random time to avoid producing load spikes on the GH actions infrastructure

env:
  CVE_CACHE_KEY: cve-db
  CVE_CACHE_DIR: ~/.m2/repository/org/owasp/dependency-check-data

jobs:
  update-vulnerability-database:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Dummy
        run: echo "Not implemented yet"
