name: "Weekly Spec Update"

on:
  workflow_dispatch:

  schedule:
    - cron: '0 0 * * SUN' # Every Sunday at midnight UTC

jobs:
  update-all-specs:
    runs-on: ubuntu-latest

    # matrix of all the spec files
    strategy:
      matrix:
        file:
          - core
          - grounding
          - orchestration
          - prompt-registry

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.BOT_SDK_JS_FOR_DOCS_REPO_PR }}

      - name: "Trigger spec update"
        run: |
          gh workflow run spec-update.yaml \
            --field file=${{ matrix.file }} \
            --field file-ref=main \
            --field create-pr=true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
